// src/App.js

// Reactを使うためのおまじない。アプリの動きを作るのに必要です。
import React from 'react';
// このJSファイルに対応する見た目の設定ファイル（App.css）を読み込みます。
import './App.css';
// 同じフォルダにある路線図の画像ファイルを読み込みます。
import lineImage from './line.png'; // ★画像ファイルをここで読み込む

// src/App.js の中、`import './App.css';` のすぐ下あたりに貼り付けてください。

// src/App.js の中、`import './App.css';` のすぐ下あたりに貼り付けてください。

// ----------------------------------------------------
// ★ここからが、あなたのアプリに表示される駅とラーメン屋さんの情報です★
// ここに駅やラーメン屋さんの情報を追加・編集していきます。
const stationData = [
  // --- 山手線主要駅 ---
 {
    id: 'tokyo',
    name: '東京駅',
    position: { top: '59.08%', left: '64.74%' },
    ramenShops: [{ name: '六厘舎', description: '言わずと知れたつけ麺の名店。', rating: 4.3 }],
  },
  {
    id: 'shinjuku',
    name: '新宿駅',
    position: { top: '41.36%', left: '30.17%' },
    ramenShops: [{ name: '麺屋 武蔵', description: '新宿を代表する行列店。つけ麺が有名。', rating: 4.2 }],
  },
  {
    id: 'shibuya',
    name: '渋谷駅',
    position: { top: '59.72%', left: '30.73%' },
    ramenShops: [{ name: 'はやし', description: '魚介豚骨のシンプルながら奥深い一杯。', rating: 4.5 }],
  },
  {
    id: 'ikebukuro',
    name: '池袋駅',
    position: { top: '25.83%', left: '33.15%' },
    ramenShops: [{ name: '無敵家', description: '豚骨醤油の超濃厚スープが魅力。', rating: 4.3 }],
  },
  {
    id: 'ueno',
    name: '上野駅',
    position: { top: '33.86%', left: '65.31%' },
    ramenShops: [{ name: '鴨to葱', description: '鴨と葱の旨味が凝縮された上品な一杯。', rating: 4.4 }],
  },
  {
    id: 'shinagawa',
    name: '品川駅',
    position: { top: '82.20%', left: '51.23%' },
    ramenShops: [{ name: 'せたが屋', description: '魚介系の風味豊かなスープ。', rating: 4.0 }],
  },
  {
    id: 'ginza',
    name: '銀座駅',
    position: { top: '64.24%', left: '67.36%' },
    ramenShops: [{ name: '銀座 篝', description: '上品な鶏白湯ラーメンが人気。', rating: 4.6 }],
  },
  {
    id: 'akihabara',
    name: '秋葉原駅',
    position: { top: '42.98%', left: '64.91%' },
    ramenShops: [{ name: '田中商店', description: '濃厚な博多豚骨ラーメン。替玉必須！', rating: 4.1 }],
  },
  {
    id: 'yurakucho',
    name: '有楽町駅',
    position: { top: '61.70%', left: '63.21%' },
    ramenShops: [],
  },
  {
    id: 'shimbashi',
    name: '新橋駅',
    position: { top: '66.30%', left: '64.51%' },
    ramenShops: [],
  },
  {
    id: 'hamamatsucho',
    name: '浜松町駅',
    position: { top: '74.33%', left: '57.49%' },
    ramenShops: [],
  },
  {
    id: 'tamachi',
    name: '田町(三田)駅',
    position: { top: '75.34%', left: '55.09%' },
    ramenShops: [],
  },
  {
    id: 'gotanda',
    name: '五反田駅',
    position: { top: '77.92%', left: '36.99%' },
    ramenShops: [],
  },
  {
    id: 'meguro',
    name: '目黒駅',
    position: { top: '73.81%', left: '34.40%' },
    ramenShops: [],
  },
  {
    id: 'ebisu',
    name: '恵比寿駅',
    position: { top: '66.99%', left: '31.31%' },
    ramenShops: [],
  },
  {
    id: 'harajuku',
    name: '原宿(明治神宮前)駅',
    position: { top: '56.13%', left: '31.31%' },
    ramenShops: [],
  },
  {
    id: 'yoyogi',
    name: '代々木駅',
    position: { top: '49.23%', left: '30.02%' },
    ramenShops: [],
  },
  {
    id: 'shinjuku-gyoemmae',
    name: '新宿御苑前駅',
    position: { top: '43.38%', left: '37.45%' },
    ramenShops: [],
  },
  {
    id: 'yotsuya',
    name: '四ツ谷駅',
    position: { top: '47.62%', left: '41.55%' },
    ramenShops: [],
  },
  {
    id: 'ichigaya',
    name: '市ヶ谷駅',
    position: { top: '44.07%', left: '46.00%' },
    ramenShops: [],
  },
  {
    id: 'iidabashi',
    name: '飯田橋駅',
    position: { top: '38.38%', left: '50.85%' },
    ramenShops: [],
  },
  {
    id: 'suidobashi',
    name: '水道橋駅',
    position: { top: '41.57%', left: '54.07%' },
    ramenShops: [],
  },
  {
    id: 'ochanomizu',
    name: '御茶ノ水駅',
    position: { top: '44.35%', left: '56.35%' },
    ramenShops: [],
  },
  {
    id: 'kanda',
    name: '神田駅',
    position: { top: '51.61%', left: '63.46%' },
    ramenShops: [],
  },
  {
    id: 'nihonbashi',
    name: '日本橋駅',
    position: { top: '56.10%', left: '73.71%' },
    ramenShops: [],
  },
 { id: 'kyobashi', name: '京橋駅', position: { top: '57.77%', left: '73.62%' }, ramenShops: [] },
 { id: 'shiodome', name: '汐留駅', position: { top: '70.02%', left: '66.56%' }, ramenShops: [] },
 { id: 'roppongi', name: '六本木駅', position: { top: '67.03%', left: '40.75%' }, ramenShops: [] },
 { id: 'azabujuban', name: '麻布十番駅', position: { top: '70.02%', left: '47.49%' }, ramenShops: [] },
 { id: 'daimon', name: '大門駅', position: { top: '69.90%', left: '57.97%' }, ramenShops: [] },
 { id: 'tocho-mae', name: '都庁前駅', position: { top: '39.91%', left: '24.62%' }, ramenShops: [] },
 { id: 'shin-okubo', name: '新大久保駅', position: { top: '31.56%', left: '30.34%' }, ramenShops: [] },
 { id: 'nakano', name: '中野駅', position: { top: '33.25%', left: '13.66%' }, ramenShops: [] },
 { id: 'kichijoji', name: '吉祥寺駅', position: { top: '33.50%', left: '6.43%' }, ramenShops: [] },
 { id: 'tachikawa', name: '立川駅', position: { top: '33.50%', left: '1.99%' }, ramenShops: [] },
 { id: 'kunitachi', name: '国立駅', position: { top: '14.41%', left: '-0.71%' }, ramenShops: [] },
 { id: 'kitasenju', name: '北千住駅', position: { top: '17.19%', left: '75.70%' }, ramenShops: [] },
 { id: 'nishi-nippori', name: '西日暮里駅', position: { top: '23.77%', left: '61.27%' }, ramenShops: [] },
 { id: 'nippori', name: '日暮里駅', position: { top: '27.60%', left: '64.54%' }, ramenShops: [] },
 { id: 'asakusa',name: '浅草駅',position: { top: '34.46%', left: '76.01%' },ramenShops: [], },
 { id: 'skytree', name: 'とうきょうスカイツリー駅', position: { top: '34.18%', left: '78.08%' }, ramenShops: [] },
 { id: 'kinshicho', name: '錦糸町駅', position: { top: '43.30%', left: '82.10%' }, ramenShops: [] },
 { id: 'monzennakacho', name: '門前仲町駅', position: { top: '56.17%', left: '79.00%' }, ramenShops: [] },
 { id: 'toyosu', name: '豊洲駅', position: { top: '67.35%', left: '81.90%' }, ramenShops: [] },
 { id: 'shinkiba', name: '新木場駅', position: { top: '63.03%', left: '84.99%' }, ramenShops: [] },
 { id: 'odaiba', name: 'お台場海浜公園駅', position: { top: '79.74%', left: '71.74%' }, ramenShops: [] },
 { id: 'ginza-icchome', name: '銀座一丁目駅', position: { top: '61.91%', left: '68.89%' }, ramenShops: [] },
 { id: 'sakuradamon', name: '桜田門駅', position: { top: '58.07%', left: '53.70%' }, ramenShops: [] },
 { id: 'kasumigaseki', name: '霞ケ関駅', position: { top: '62.95%', left: '54.38%' }, ramenShops: [] },
 { id: 'nagatacho', name: '永田町駅', position: { top: '57.46%', left: '47.49%' }, ramenShops: [] },
{ id: 'kokkai-gijidomae', name: '国会議事堂前駅', position: { top: '61.70%', left: '49.49%' }, ramenShops: [] },
{ id: 'roppongi-itchome', name: '六本木一丁目駅', position: { top: '68.32%', left: '48.21%' }, ramenShops: [] },
{ id: 'kamiyacho', name: '神谷町駅', position: { top: '66.50%', left: '51.28%' }, ramenShops: [] },
{ id: 'shiba-koen', name: '芝公園駅', position: { top: '71.39%', left: '55.63%' }, ramenShops: [] },
{ id: 'okachimachi', name: '御徒町駅', position: { top: '68.44%', left: '56.72%' }, ramenShops: [] },
{ id: 'ryogoku', name: '両国駅', position: { top: '42.70%', left: '77.77%' }, ramenShops: [] },
{ id: 'sumiyoshi', name: '住吉駅', position: { top: '47.86%', left: '82.16%' }, ramenShops: [] },
{ id: 'higashi-ginza', name: '東銀座駅', position: { top: '67.03%', left: '70.17%' }, ramenShops: [] },
{ id: 'tsukiji', name: '築地駅', position: { top: '69.05%', left: '72.25%' }, ramenShops: [] },
{ id: 'hatchobori', name: '八丁堀駅', position: { top: '63.24%', left: '77.18%' }, ramenShops: [] },
{ id: 'kayabacho', name: '茅場町駅', position: { top: '57.38%', left: '76.89%' }, ramenShops: [] },
{ id: 'suitengumae', name: '水天宮前駅', position: { top: '54.56%', left: '76.55%' }, ramenShops: [] },
{ id: 'ningyocho', name: '人形町駅', position: { top: '52.70%', left: '74.13%' }, ramenShops: [] },
{ id: 'kodemmacho', name: '小伝馬町駅', position: { top: '48.99%', left: '70.15%' }, ramenShops: [] },
{ id: 'shin-nihonbashi', name: '新日本橋(三越前)駅', position: { top: '52.10%', left: '69.95%' }, ramenShops: [] },
{ id: 'jinbocho', name: '神保町駅', position: { top: '51.05%', left: '53.84%' }, ramenShops: [] },
{ id: 'takebashi', name: '竹橋駅', position: { top: '54.80%', left: '50.57%' }, ramenShops: [] },
{ id: 'kudanshita', name: '九段下駅', position: { top: '49.96%', left: '50.65%' }, ramenShops: [] },
{ id: 'hongo-sanchome', name: '本郷三丁目駅', position: { top: '35.67%', left: '55.23%' }, ramenShops: [] },
{ id: 'korakuen', name: '後楽園駅', position: { top: '35.75%', left: '58.31%' }, ramenShops: [] },
{ id: 'kasuga', name: '春日駅', position: { top: '31.40%', left: '54.09%' }, ramenShops: [] },
{ id: 'myogadani', name: '茗荷谷駅', position: { top: '24.42%', left: '46.27%' }, ramenShops: [] },
{ id: 'kanamecho', name: '要町駅', position: { top: '21.27%', left: '29.25%' }, ramenShops: [] },
{ id: 'senkawa', name: '千川駅', position: { top: '19.01%', left: '27.72%' }, ramenShops: [] },
{ id: 'kotake-mukaihara', name: '小竹向原駅', position: { top: '16.46%', left: '24.30%' }, ramenShops: [] },
{ id: 'nerima', name: '練馬駅', position: { top: '20.78%', left: '17.39%' }, ramenShops: [] },
{ id: 'ekoda', name: '江古田駅', position: { top: '20.90%', left: '24.07%' }, ramenShops: [] },
{ id: 'takadanobaba', name: '高田馬場駅', position: { top: '29.66%', left: '28.80%' }, ramenShops: [] },
{ id: 'waseda', name: '早稲田駅', position: { top: '34.26%', left: '41.44%' }, ramenShops: [] },
{ id: 'kagurazaka', name: '神楽坂駅', position: { top: '34.26%', left: '44.54%' }, ramenShops: [] },
{ id: 'higashi-nakano', name: '東中野駅', position: { top: '34.18%', left: '17.36%' }, ramenShops: [] },
{ id: 'nakano-sakaue', name: '中野坂上駅', position: { top: '38.01%', left: '18.95%' }, ramenShops: [] },
{ id: 'nishishinjuku-gochome', name: '西新宿五丁目駅', position: { top: '40.03%', left: '22.28%' }, ramenShops: [] },
{ id: 'hatagaya', name: '幡ヶ谷駅', position: { top: '46.85%', left: '24.22%' }, ramenShops: [] },
{ id: 'sasazuka', name: '笹塚駅', position: { top: '47.79%', left: '20.49%' }, ramenShops: [] },
{ id: 'meidaimae', name: '明大前駅', position: { top: '48.34%', left: '16.22%' }, ramenShops: [] },
  
 { id: 'kokkai-gijidomae', name: '国会議事堂前駅', position: { top: '61.70%', left: '49.49%' }, ramenShops: [] },
 { id: 'roppongi-itchome', name: '六本木一丁目駅', position: { top: '68.32%', left: '48.21%' }, ramenShops: [] },
 { id: 'kamiyacho', name: '神谷町駅', position: { top: '66.50%', left: '51.28%' }, ramenShops: [] },
 { id: 'shiba-koen', name: '芝公園駅', position: { top: '71.39%', left: '55.63%' }, ramenShops: [] },
 { id: 'okachimachi', name: '御徒町駅', position: { top: '68.44%', left: '56.72%' }, ramenShops: [] },
 { id: 'ryogoku', name: '両国駅', position: { top: '42.70%', left: '77.77%' }, ramenShops: [] },
 { id: 'sumiyoshi', name: '住吉駅', position: { top: '47.86%', left: '82.16%' }, ramenShops: [] },
 { id: 'higashi-ginza', name: '東銀座駅', position: { top: '67.03%', left: '70.17%' }, ramenShops: [] },
 { id: 'tsukiji', name: '築地駅', position: { top: '69.05%', left: '72.25%' }, ramenShops: [] },
 { id: 'hatchobori', name: '八丁堀駅', position: { top: '63.24%', left: '77.18%' }, ramenShops: [] },
 { id: 'kayabacho', name: '茅場町駅', position: { top: '57.38%', left: '76.89%' }, ramenShops: [] },
 { id: 'suitengumae', name: '水天宮前駅', position: { top: '54.56%', left: '76.55%' }, ramenShops: [] },
 { id: 'ningyocho', name: '人形町駅', position: { top: '52.70%', left: '74.13%' }, ramenShops: [] },
 { id: 'kodemmacho', name: '小伝馬町駅', position: { top: '48.99%', left: '70.15%' }, ramenShops: [] },
 { id: 'shin-nihonbashi', name: '新日本橋(三越前)駅', position: { top: '52.10%', left: '69.95%' }, ramenShops: [] },
 { id: 'jinbocho', name: '神保町駅', position: { top: '51.05%', left: '53.84%' }, ramenShops: [] },
 { id: 'takebashi', name: '竹橋駅', position: { top: '54.80%', left: '50.57%' }, ramenShops: [] },
 { id: 'kudanshita', name: '九段下駅', position: { top: '49.96%', left: '50.65%' }, ramenShops: [] },
 { id: 'hongo-sanchome', name: '本郷三丁目駅', position: { top: '35.67%', left: '55.23%' }, ramenShops: [] },
 { id: 'korakuen', name: '後楽園駅', position: { top: '35.75%', left: '58.31%' }, ramenShops: [] },
 { id: 'kasuga', name: '春日駅', position: { top: '31.40%', left: '54.09%' }, ramenShops: [] },
 { id: 'myogadani', name: '茗荷谷駅', position: { top: '24.42%', left: '46.27%' }, ramenShops: [] },
 { id: 'kanamecho', name: '要町駅', position: { top: '21.27%', left: '29.25%' }, ramenShops: [] },
 { id: 'senkawa', name: '千川駅', position: { top: '19.01%', left: '27.72%' }, ramenShops: [] },
 { id: 'kotake-mukaihara', name: '小竹向原駅', position: { top: '16.46%', left: '24.30%' }, ramenShops: [] },
 { id: 'nerima', name: '練馬駅', position: { top: '20.78%', left: '17.39%' }, ramenShops: [] },
 { id: 'ekoda', name: '江古田駅', position: { top: '20.90%', left: '24.07%' }, ramenShops: [] },
 { id: 'takadanobaba', name: '高田馬場駅', position: { top: '29.66%', left: '28.80%' }, ramenShops: [] },
 { id: 'waseda', name: '早稲田駅', position: { top: '34.26%', left: '41.44%' }, ramenShops: [] },
 { id: 'kagurazaka', name: '神楽坂駅', position: { top: '34.26%', left: '44.54%' }, ramenShops: [] },
 { id: 'higashi-nakano', name: '東中野駅', position: { top: '34.18%', left: '17.36%' }, ramenShops: [] },
 { id: 'nakano-sakaue', name: '中野坂上駅', position: { top: '38.01%', left: '18.95%' }, ramenShops: [] },
 { id: 'nishishinjuku-gochome', name: '西新宿五丁目駅', position: { top: '40.03%', left: '22.28%' }, ramenShops: [] },
 { id: 'hatagaya', name: '幡ヶ谷駅', position: { top: '46.85%', left: '24.22%' }, ramenShops: [] },
 { id: 'sasazuka', name: '笹塚駅', position: { top: '47.79%', left: '20.49%' }, ramenShops: [] },
 { id: 'meidaimae', name: '明大前駅', position: { top: '48.34%', left: '16.22%' }, ramenShops: [] },
 { id: 'shimo-kitazawa', name: '下北沢駅', position: { top: '55.08%', left: '15.93%' }, ramenShops: [] },
 { id: 'naka-meguro', name: '中目黒駅', position: { top: '66.91%', left: '26.18%' }, ramenShops: [] },
 { id: 'jiyugaoka', name: '自由が丘駅', position: { top: '75.10%', left: '19.72%' }, ramenShops: [] },
 { id: 'okayama', name: '大岡山駅', position: { top: '76.39%', left: '24.33%' }, ramenShops: [] },
 { id: 'musashi-kosugi', name: '武蔵小杉駅', position: { top:'84.14%', left:'11.72%' }, ramenShops: [] },
 { id: 'musashi-kosugi-jr', name: 'JR武蔵小杉駅', position: { top: '88.54%', left: '10.67%'}, ramenShops: [] },
 { id: 'den-en-chofu', name: '田園調布駅', position: { top: '78.73%', left: '18.33%' }, ramenShops: [] },
 { id: 'futako-tamagawa', name: '二子玉川駅', position: { top: '67.03%', left: '8.88%' }, ramenShops: [] },
 { id: 'setagaya-daita', name: '世田谷代田駅', position: { top: '55.00%', left: '13.80%' }, ramenShops: [] },
 { id: 'kugayama', name: '久我山駅', position: { top: '39.02%', left: '9.87%' }, ramenShops: [] },
 { id: 'ogikubo', name: '荻窪駅', position: { top: '33.30%', left: '9.53%' }, ramenShops: [] },
 { id: 'minami-senju', name: '南千住駅', position: { top: '26.35%', left: '75.55%' }, ramenShops: [] },
 { id: 'machiya', name: '町屋駅', position: { top: '16.83%', left: '70.83%' }, ramenShops: [] },
 { id: 'itabashi', name: '板橋駅', position: { top: '19.82%', left: '37.20%' }, ramenShops: [] },
 { id: 'mukojima', name: '東向島駅', position: { top: '28.69%', left: '81.65%' }, ramenShops: [] },
 { id: 'higashi-jujo', name: '東十条駅', position: { top: '9.89%', left: '43.11%' }, ramenShops: [] },
 { id: 'oji-kamiya', name: '王子神谷駅', position: { top: '9.04%', left: '48.72%' }, ramenShops: [] },
 { id: 'shin-itabashi', name: '新板橋駅', position: { top: '13.96%', left: '36.60%' }, ramenShops: [] },
 { id: 'sugamo', name: '巣鴨駅', position: { top: '21.23%', left: '46.99%' }, ramenShops: [] },
 { id: 'komagome', name: '駒込駅', position: { top: '21.47%', left: '53.10%' }, ramenShops: [] },
 { id: 'tabata', name: '田端駅', position: { top: '24.33%', left: '56.72%' }, ramenShops: [] },
 { id: 'oshima', name: '大島駅', position: { top: '47.86%', left: '85.43%' }, ramenShops: [] },
 { id: 'nishi-ojima', name: '西大島駅', position: { top: '47.78%', left: '84.04%' }, ramenShops: [] },
 { id: 'higashi-ojima', name: '東大島駅', position: { top: '47.78%', left: '86.70%' }, ramenShops: [] },
 { id: 'funabori', name: '船堀駅', position: { top: '47.74%', left: '88.03%' }, ramenShops: [] },
 { id: 'ichinoe', name: '一之江駅', position: { top: '47.82%', left: '89.33%' }, ramenShops: [] },
 { id: 'mizue', name: '瑞江駅', position: { top: '47.86%', left: '90.71%' }, ramenShops: [] },
 { id: 'shinozaki', name: '篠崎駅', position: { top: '47.82%', left: '91.90%' }, ramenShops: [] },
 { id: 'motoyawata', name: '本八幡駅', position: { top: '47.21%', left: '94.02%' }, ramenShops: [] },
 { id: 'koenji', name: '高円寺駅', position: { top: '33.30%', left: '12.09%' }, ramenShops: [] },
 { id: 'asagaya', name: '阿佐ケ谷駅', position: { top: '33.25%', left: '10.87%' }, ramenShops: [] },
 { id: 'nishi-ogikubo', name: '西荻窪駅', position: { top: '33.25%', left: '7.94%' }, ramenShops: [] },
 { id: 'mitaka', name: '三鷹駅', position: { top: '33.25%', left: '0.85%' }, ramenShops: [] },
 { id: 'musashisakai', name: '武蔵境駅', position: { top: '27.52%', left: '4.67%' }, ramenShops: [] },
 { id: 'takaido', name: '高井戸駅', position: { top: '41.93%', left: '11.87%' }, ramenShops: [] },
 { id: 'kugayama-keio', name: '久我山駅', position: { top: '39.02%', left: '9.84%' }, ramenShops: [] },
 { id: 'inokashira-koen', name: '井の頭公園駅', position: { top: '36.12%', left: '7.79%' }, ramenShops: [] },
 { id: 'shimo-takaido', name: '下高井戸駅', position: { top: '48.59%', left: '10.67%' }, ramenShops: [] },
 { id: 'sakurajosui', name: '桜上水駅', position: { top: '48.39%', left: '8.14%' }, ramenShops: [] },
 { id: 'chitose-karasuyama', name: '千歳烏山駅', position: { top: '55.16%', left: '8.05%' }, ramenShops: [] },
 { id: 'shinjuku-sanchome', name: '新宿三丁目駅', position: { top: '41.24%', left: '35.46%' }, ramenShops: [] },
 { id: 'higashi-shinjuku', name: '東新宿駅', position: { top: '37.33%', left: '35.37%' }, ramenShops: [] },
 { id: 'nishi-waseda', name: '西早稲田駅', position: { top: '35.63%', left: '35.77%' }, ramenShops: [] },
 { id: 'zoshigaya', name: '雑司が谷駅', position: { top: '31.03%', left: '35.57%' }, ramenShops: [] },
 { id: 'gokokuji', name: '護国寺駅', position: { top: '29.49%', left: '45.16%' }, ramenShops: [] },
 { id: 'edogawabashi', name: '江戸川橋駅', position: { top: '31.03%', left: '45.16%' }, ramenShops: [] },
 { id: 'akabane', name: '赤羽駅', position: { top: '7.99%', left: '38.87%' }, ramenShops: [] },
 { id: 'kita-akabane', name: '北赤羽駅', position: { top: '6.78%', left: '36.65%' }, ramenShops: [] },
 { id: 'arakawa-kosen', name: '荒川区役所前', position: { top: '23.04%', left: '72.06%' }, ramenShops: [] },
 { id: 'hiken-koen', name: '飛鳥山', position: { top: '11.62%', left: '49.37%' }, ramenShops: [] },
 { id: 'kasai', name: '葛西駅', position: { top: '55.81%', left: '87.85%' }, ramenShops: [] },
 { id: 'urayasu', name: '浦安駅', position: { top: '55.85%', left: '89.16%' }, ramenShops: [] },
 { id: 'gyotoku', name: '行徳駅', position: { top: '55.93%', left: '91.55%' }, ramenShops: [] },
 { id: 'myoden', name: '妙典駅', position: { top: '56.05%', left: '92.80%' }, ramenShops: [] },
 
 { id: 'kokkai-gijidomae', name: '国会議事堂前駅', position: { top: '61.70%', left: '49.49%' }, ramenShops: [] },
 { id: 'roppongi-itchome', name: '六本木一丁目駅', position: { top: '68.32%', left: '48.21%' }, ramenShops: [] },
 { id: 'kamiyacho', name: '神谷町駅', position: { top: '66.50%', left: '51.28%' }, ramenShops: [] },
 { id: 'shiba-koen', name: '芝公園駅', position: { top: '71.39%', left: '55.63%' }, ramenShops: [] },
 { id: 'okachimachi', name: '御徒町駅', position: { top: '68.44%', left: '56.72%' }, ramenShops: [] },
 { id: 'ryogoku', name: '両国駅', position: { top: '42.70%', left: '77.77%' }, ramenShops: [] },
 { id: 'sumiyoshi', name: '住吉駅', position: { top: '47.86%', left: '82.16%' }, ramenShops: [] },
 { id: 'higashi-ginza', name: '東銀座駅', position: { top: '67.03%', left: '70.17%' }, ramenShops: [] },
 { id: 'tsukiji', name: '築地駅', position: { top: '69.05%', left: '72.25%' }, ramenShops: [] },
 { id: 'hatchobori', name: '八丁堀駅', position: { top: '63.24%', left: '77.18%' }, ramenShops: [] },
 { id: 'kayabacho', name: '茅場町駅', position: { top: '57.38%', left: '76.89%' }, ramenShops: [] },
 { id: 'suitengumae', name: '水天宮前駅', position: { top: '54.56%', left: '76.55%' }, ramenShops: [] },
 { id: 'ningyocho', name: '人形町駅', position: { top: '52.70%', left: '74.13%' }, ramenShops: [] },
 { id: 'kodemmacho', name: '小伝馬町駅', position: { top: '48.99%', left: '70.15%' }, ramenShops: [] },
 { id: 'shin-nihonbashi', name: '新日本橋(三越前)駅', position: { top: '52.10%', left: '69.95%' }, ramenShops: [] },
 { id: 'jinbocho', name: '神保町駅', position: { top: '51.05%', left: '53.84%' }, ramenShops: [] },
 { id: 'takebashi', name: '竹橋駅', position: { top: '54.80%', left: '50.57%' }, ramenShops: [] },
 { id: 'kudanshita', name: '九段下駅', position: { top: '49.96%', left: '50.65%' }, ramenShops: [] },
 { id: 'hongo-sanchome', name: '本郷三丁目駅', position: { top: '35.67%', left: '55.23%' }, ramenShops: [] },
 { id: 'korakuen', name: '後楽園駅', position: { top: '35.75%', left: '58.31%' }, ramenShops: [] },
 { id: 'kasuga', name: '春日駅', position: { top: '31.40%', left: '54.09%' }, ramenShops: [] },
 { id: 'myogadani', name: '茗荷谷駅', position: { top: '24.42%', left: '46.27%' }, ramenShops: [] },
 { id: 'kanamecho', name: '要町駅', position: { top: '21.27%', left: '29.25%' }, ramenShops: [] },
 { id: 'senkawa', name: '千川駅', position: { top: '19.01%', left: '27.72%' }, ramenShops: [] },
 { id: 'kotake-mukaihara', name: '小竹向原駅', position: { top: '16.46%', left: '24.30%' }, ramenShops: [] },
 { id: 'nerima', name: '練馬駅', position: { top: '20.78%', left: '17.39%' }, ramenShops: [] },
 { id: 'ekoda', name: '江古田駅', position: { top: '20.90%', left: '24.07%' }, ramenShops: [] },
 { id: 'takadanobaba', name: '高田馬場駅', position: { top: '29.66%', left: '28.80%' }, ramenShops: [] },
 { id: 'waseda', name: '早稲田駅', position: { top: '34.26%', left: '41.44%' }, ramenShops: [] },
 { id: 'kagurazaka', name: '神楽坂駅', position: { top: '34.26%', left: '44.54%' }, ramenShops: [] },
 { id: 'higashi-nakano', name: '東中野駅', position: { top: '34.18%', left: '17.36%' }, ramenShops: [] },
 { id: 'nakano-sakaue', name: '中野坂上駅', position: { top: '38.01%', left: '18.95%' }, ramenShops: [] },
 { id: 'nishishinjuku-gochome', name: '西新宿五丁目駅', position: { top: '40.03%', left: '22.28%' }, ramenShops: [] },
 { id: 'hatagaya', name: '幡ヶ谷駅', position: { top: '46.85%', left: '24.22%' }, ramenShops: [] },
 { id: 'sasazuka', name: '笹塚駅', position: { top: '47.79%', left: '20.49%' }, ramenShops: [] },
 { id: 'meidaimae', name: '明大前駅', position: { top: '48.34%', left: '16.22%' }, ramenShops: [] },
 { id: 'shimo-kitazawa', name: '下北沢駅', position: { top: '55.08%', left: '15.93%' }, ramenShops: [] },
 { id: 'naka-meguro', name: '中目黒駅', position: { top: '66.91%', left: '26.18%' }, ramenShops: [] },
 { id: 'jiyugaoka', name: '自由が丘駅', position: { top: '75.10%', left: '19.72%' }, ramenShops: [] },
 { id: 'okayama', name: '大岡山駅', position: { top: '76.39%', left: '24.33%' }, ramenShops: [] },
 { id: 'musashi-kosugi', name: '武蔵小杉駅', position: { top:'84.14%', left:'11.72%' }, ramenShops: [] },
 { id: 'musashi-kosugi-jr', name: 'JR武蔵小杉駅', position: { top: '88.54%', left: '10.67%'}, ramenShops: [] },
 { id: 'den-en-chofu', name: '田園調布駅', position: { top: '78.73%', left: '18.33%' }, ramenShops: [] },
 { id: 'futako-tamagawa', name: '二子玉川駅', position: { top: '67.03%', left: '8.88%' }, ramenShops: [] },
 { id: 'setagaya-daita', name: '世田谷代田駅', position: { top: '55.00%', left: '13.80%' }, ramenShops: [] },
 { id: 'kugayama', name: '久我山駅', position: { top: '39.02%', left: '9.87%' }, ramenShops: [] },
 { id: 'ogikubo', name: '荻窪駅', position: { top: '33.30%', left: '9.53%' }, ramenShops: [] },
 { id: 'minami-senju', name: '南千住駅', position: { top: '26.35%', left: '75.55%' }, ramenShops: [] },
 { id: 'machiya', name: '町屋駅', position: { top: '16.83%', left: '70.83%' }, ramenShops: [] },
 { id: 'itabashi', name: '板橋駅', position: { top: '19.82%', left: '37.20%' }, ramenShops: [] },
 { id: 'mukojima', name: '東向島駅', position: { top: '28.69%', left: '81.65%' }, ramenShops: [] },
 { id: 'higashi-jujo', name: '東十条駅', position: { top: '9.89%', left: '43.11%' }, ramenShops: [] },
 { id: 'oji-kamiya', name: '王子神谷駅', position: { top: '9.04%', left: '48.72%' }, ramenShops: [] },
 { id: 'shin-itabashi', name: '新板橋駅', position: { top: '13.96%', left: '36.60%' }, ramenShops: [] },
 { id: 'sugamo', name: '巣鴨駅', position: { top: '21.23%', left: '46.99%' }, ramenShops: [] },
 { id: 'komagome', name: '駒込駅', position: { top: '21.47%', left: '53.10%' }, ramenShops: [] },
 { id: 'tabata', name: '田端駅', position: { top: '24.33%', left: '56.72%' }, ramenShops: [] },
 { id: 'oshima', name: '大島駅', position: { top: '47.86%', left: '85.43%' }, ramenShops: [] },
 { id: 'nishi-ojima', name: '西大島駅', position: { top: '47.78%', left: '84.04%' }, ramenShops: [] },
 { id: 'higashi-ojima', name: '東大島駅', position: { top: '47.78%', left: '86.70%' }, ramenShops: [] },
 { id: 'funabori', name: '船堀駅', position: { top: '47.74%', left: '88.03%' }, ramenShops: [] },
 { id: 'ichinoe', name: '一之江駅', position: { top: '47.82%', left: '89.33%' }, ramenShops: [] },
 { id: 'mizue', name: '瑞江駅', position: { top: '47.86%', left: '90.71%' }, ramenShops: [] },
 { id: 'shinozaki', name: '篠崎駅', position: { top: '47.82%', left: '91.90%' }, ramenShops: [] },
 { id: 'motoyawata', name: '本八幡駅', position: { top: '47.21%', left: '94.02%' }, ramenShops: [] },
 { id: 'koenji', name: '高円寺駅', position: { top: '33.30%', left: '12.09%' }, ramenShops: [] },
 { id: 'asagaya', name: '阿佐ケ谷駅', position: { top: '33.25%', left: '10.87%' }, ramenShops: [] },
 { id: 'nishi-ogikubo', name: '西荻窪駅', position: { top: '33.25%', left: '7.94%' }, ramenShops: [] },
 { id: 'mitaka', name: '三鷹駅', position: { top: '33.25%', left: '0.85%' }, ramenShops: [] },
 { id: 'musashisakai', name: '武蔵境駅', position: { top: '27.52%', left: '4.67%' }, ramenShops: [] },
 { id: 'takaido', name: '高井戸駅', position: { top: '41.93%', left: '11.87%' }, ramenShops: [] },
 { id: 'kugayama-keio', name: '久我山駅', position: { top: '39.02%', left: '9.84%' }, ramenShops: [] },
 { id: 'inokashira-koen', name: '井の頭公園駅', position: { top: '36.12%', left: '7.79%' }, ramenShops: [] },
 { id: 'shimo-takaido', name: '下高井戸駅', position: { top: '48.59%', left: '10.67%' }, ramenShops: [] },
 { id: 'sakurajosui', name: '桜上水駅', position: { top: '48.39%', left: '8.14%' }, ramenShops: [] },
 { id: 'chitose-karasuyama', name: '千歳烏山駅', position: { top: '55.16%', left: '8.05%' }, ramenShops: [] },
 { id: 'shinjuku-sanchome', name: '新宿三丁目駅', position: { top: '41.24%', left: '35.46%' }, ramenShops: [] },
 { id: 'higashi-shinjuku', name: '東新宿駅', position: { top: '37.33%', left: '35.37%' }, ramenShops: [] },
 { id: 'nishi-waseda', name: '西早稲田駅', position: { top: '35.63%', left: '35.77%' }, ramenShops: [] },
 { id: 'zoshigaya', name: '雑司が谷駅', position: { top: '31.03%', left: '35.57%' }, ramenShops: [] },
 { id: 'gokokuji', name: '護国寺駅', position: { top: '29.49%', left: '45.16%' }, ramenShops: [] },
 { id: 'edogawabashi', name: '江戸川橋駅', position: { top: '31.03%', left: '45.16%' }, ramenShops: [] },
 { id: 'akabane', name: '赤羽駅', position: { top: '7.99%', left: '38.87%' }, ramenShops: [] },
 { id: 'kita-akabane', name: '北赤羽駅', position: { top: '6.78%', left: '36.65%' }, ramenShops: [] },
 { id: 'arakawa-kosen', name: '荒川区役所前', position: { top: '23.04%', left: '72.06%' }, ramenShops: [] },
 { id: 'hiken-koen', name: '飛鳥山', position: { top: '11.62%', left: '49.37%' }, ramenShops: [] },
 { id: 'kasai', name: '葛西駅', position: { top: '55.81%', left: '87.85%' }, ramenShops: [] },
 { id: 'urayasu', name: '浦安駅', position: { top: '55.85%', left: '89.16%' }, ramenShops: [] },
 { id: 'gyotoku', name: '行徳駅', position: { top: '55.93%', left: '91.55%' }, ramenShops: [] },
 { id: 'myoden', name: '妙典駅', position: { top: '56.05%', left: '92.80%' }, ramenShops: [] },
 
  { id: 'shin-otsuka', name: '新大塚駅', position: { top: '24.46%', left: '43.77%' }, ramenShops: [] },
 { id: 'shimo-maruko', name: '下丸子', position: { top: '93.14%', left: '26.38%' }, ramenShops: []}, 
 { id: 'musashi-nitta', name: '武蔵新田駅', position: { top: '93.14%', left: '31.20%' }, ramenShops: []},
 { id: 'yaguchinowatashi', name: '矢口渡', position: { top: '93.10%', left: '36.23%' }, ramenShops: []}, 
 { id: 'numabe', name: '沼部', position: { top: '85.35%', left: '16.08%' }, ramenShops: []}, 
 { id: 'okayama-meguro', name: '大岡山', position: { top: '76.23%', left: '24.27%' }, ramenShops: [] }, 
 { id: 'senzoku', name: '洗足', position: { top: '74.13%', left: '25.53%' }, ramenShops: [] }, 
 { id: 'musashi-koyama-meguro', name: '武蔵小山', position: { top: '73.73%', left: '29.42%' }, ramenShops: [] },  
 { id: 'hibarigaoka', name: 'ひばりヶ丘', position: { top: '20.98%', left: '5.92%' }, ramenShops: [] }, 
 { id: 'heiwadai', name: '平和台', position: { top: '7.95%', left: '15.88%' }, ramenShops: [] }, 
 { id: 'wakoshi', name: '和光市', position: { top: '6.10%', left: '8.25%' }, ramenShops: [] }, 
 { id: 'asaka', name: '朝霞', position: { top: '5.61%', left: '5.55%' }, ramenShops: [] }, 
 { id: 'ukimafunado-jr', name: '浮間舟渡駅', position: { top: '5.12%', left: '35.51%' }, ramenShops: [] },
 { id: 'itabashihoncho-jr', name: '板橋本町駅', position: { top: '10.70%', left: '34.21%' }, ramenShops: [] },
 { id: 'otsuka-jr-yamanote', name: '大塚駅', position: { top: '21.14%', left: '39.89%' }, ramenShops: [] },
 { id: 'mejiro-jr-yamanote', name: '目白駅', position: { top: '27.64%', left: '31.16%' }, ramenShops: [] },
 { id: 'okachimachi-jr-yamanote', name: '御徒町駅', position: { top: '39.87%', left: '63.66%' }, ramenShops: [] },
 { id: 'gaien-mae', name: '外苑前駅', position: { top: '59.89%', left: '38.16%' }, ramenShops: [] },
 { id: 'korakuen-m', name: '後楽園駅', position: { top: '34.87%', left: '53.10%' }, ramenShops: [] },
 { id: 'otemachi-m', name: '大手町駅', position: { top: '55.25%', left: '57.97%' }, ramenShops: [] },
 { id: 'naka-okachimachi-h', name: '仲御徒町駅', position: { top: '40.03%', left: '67.50%' }, ramenShops: [] },
 { id: 'tatsumi-y', name: '辰巳駅', position: { top: '66.83%', left: '84.04%' }, ramenShops: [] },
 { id: 'nogizaka', name: '乃木坂駅', position: { top: '61.70%', left: '36.45%' }, ramenShops: [] },
 { id: 'akase', name: '赤坂駅', position: { top: '63.07%', left: '39.10%' }, ramenShops: [] },
 { id: 'keisei-takasago', name: '京成高砂駅', position: { top: '20.42%', left: '87.65%' }, ramenShops: [] },
 { id: 'keisei-koiwa', name: '京成小岩駅', position: { top: '20.10%', left: '89.44%' }, ramenShops: [] },
 { id: 'tokyu-fudomae', name: '不動前駅', position: { top: '73.81%', left: '30.76%' }, ramenShops: [] },
 { id: 'maihama-jr', name: '舞浜駅', position: { top: '63.11%', left: '92.90%' }, ramenShops: [] },
 { id: 'kokusai-tenjijo-rinkai', name: '国際展示場駅', position: { top: '80.39%', left: '78.52%' }, ramenShops: [] },
 { id: 'kachidoki', name: '勝どき駅', position: { top: '71.31%', left: '77.89%' }, ramenShops: [] },
 { id: 'odakyu-seijogakuen-mae', name: '成城学園前駅', position: { top: '55.00%', left: '5.66%' }, ramenShops: [] },
 { id: 'uchisaiwaicho', name: '内幸町駅', position: { top: '64.85%', left: '56.66%' }, ramenShops: [] },
 {id:'tamagawa',name:'多摩川',position:{top:'79.05%',left:'16.16%'},ramenShops:[]},
 {id:'motosumiyosi',name:'元住吉',position:{top:'83.82%',left:'8.56%'},ramenShops:[]},
 {id:'unoki',name:'鵜の木',position:{top:'93.26%',left:'20.83%'},ramenShops:[]},
 {id:'kugahara',name:'久が原',position:{top:'92.62%',left:'21.85%'},ramenShops:[]},
 {id:'ontakeyama',name:'御嶽山',position:{top:'83.37%',left:'19.34%'},ramenShops:[]},
 {id:'yukigawaootuka',name:'雪が谷大塚',position:{top:'80.47%',left:'20.89%'},ramenShops:[]},
 {id:'isikawadai',name:'石川台',position:{top:'80.47%',left:'22.11%'},ramenShops:[]},
 {id:'senzokuike',name:'洗足池',position:{top:'80.47%',left:'23.55%'},ramenShops:[]},
 {id:'nagahara',name:'長原',position:{top:'80.47%',left:'24.89%'},ramenShops:[]},
 {id:'hatanodai',name:'旗の台',position:{top:'79.90%',left:'27.69%'},ramenShops:[]},
 {id:'ebaranakanobu',name:'荏原中延',position:{top:'77.68%',left:'30.36%'},ramenShops:[]},
 {id:'togosiginza',name:'戸越銀座',position:{top:'77.68%',left:'31.47%'},ramenShops:[]},
 {id:'oosakihirokouji',name:'大崎広小路',position:{top:'77.68%',left:'32.58%'},ramenShops:[]},
 {id:'tidorimati',name:'千鳥町',position:{top:'92.86%',left:'30.33%'},ramenShops:[]},
 {id:'ikegami',name:'池上',position:{top:'92.86%',left:'34.46%'},ramenShops:[]},
 {id:'hasunuma',name:'蓮沼',position:{top:'92.86%',left:'38.65%'},ramenShops:[]},
 {id:'oomori',name:'大森',position:{top:'93.66%',left:'45.82%'},ramenShops:[]},
 {id:'kaminakazato',name:'上中里',position:{top:'19.53%',left:'54.21%'},ramenShops:[]},
 {id:'oji',name:'王子',position:{top:'9.56%',left:'51.08%'},ramenShops:[]},
 {id:'takatu',name:'高津',position:{top:'67.19%',left:'4.72%'},ramenShops:[]},
 {id:'hutakosinti',name:'二子新地',position:{top:'67.19%',left:'5.75%'},ramenShops:[]},
 {id:'kaminoge',name:'上野毛',position:{top:'68.80%',left:'11.81%'},ramenShops:[]},
 {id:'todoroki',name:'等々力',position:{top:'70.30%',left:'12.95%'},ramenShops:[]},
 {id:'oyamadai',name:'尾山台',position:{top:'71.91%',left:'14.20%'},ramenShops:[]},
 {id:'kuhonbutu',name:'九品仏',position:{top:'73.61%',left:'15.39%'},ramenShops:[]},
 {id:'midorigaoka',name:'緑ヶ丘',position:{top:'75.22%',left:'22.31%'},ramenShops:[]},
 {id:'kamitisato',name:'北千束',position:{top:'77.96%',left:'26.15%'},ramenShops:[]},
 {id:'ebaramati',name:'荏原町',position:{top:'83.70%',left:'30.28%'},ramenShops:[]},
 {id:'nakanobu',name:'中延',position:{top:'83.70%',left:'30.28%'},ramenShops:[]},
 {id:'togosiginza',name:'戸越公園',position:{top:'84.83%',left:'38.28%'},ramenShops:[]},
 {id:'simokamiaki',name:'下神明',position:{top:'84.79%',left:'45.14%'},ramenShops:[]},
 {id:'nisiooi',name:'西大井',position:{top:'88.39%',left:'42.34%'},ramenShops:[]},
 {id:'oosaki',name:'大崎',position:{top:'80.14%',left:'42.63%'},ramenShops:[]},
 {id:'daikanyama',name:'代官山',position:{top:'62.06%',left:'29.14%'},ramenShops:[]},
 {id:'yutenji',name:'祐天寺',position:{top:'69.57%',left:'24.21%'},ramenShops:[]},
 {id:'gakugeidaigaku',name:'学芸大学',position:{top:'71.63%',left:'22.06%'},ramenShops:[]},
 {id:'toritudaigaku',name:'都立大学',position:{top:'73.36%',left:'20.26%'},ramenShops:[]},
 {id:'sinmaruko',name:'新丸子',position:{top:'79.05%',left:'14.09%'},ramenShops:[]},
 {id:'magome',name:'馬込',position:{top:'86.56%',left:'31.93%'},ramenShops:[]},
 {id:'togosi',name:'戸越',position:{top:'80.87%',left:'36.03%'},ramenShops:[]},
 {id:'takaramati',name:'宝町',position:{top:'61.18%',left:'74.61%'},ramenShops:[]},
 {id:'nhigasinihonbasi',name:'東日本橋',position:{top:'46.21%',left:'76.07%'},ramenShops:[]},
 {id:'asakusabasi',name:'浅草橋',position:{top:'42.78%',left:'74.73%'},ramenShops:[]},
 {id:'kuramae',name:'蔵前',position:{top:'38.58%',left:'74.84%'},ramenShops:[]},
 {id:'honjoagatumabasi',name:'本所我妻橋',position:{top:'35.35%',left:'77.52%'},ramenShops:[]},
 {id:'osiage',name:'押上',position:{top:'35.47%',left:'81.36%'},ramenShops:[]},
 {id:'keiseihunabiki',name:'京成船曳',position:{top:'30.06%',left:'84.64%'},ramenShops:[]},
 {id:'yahiro',name:'八広',position:{top:'28.29%',left:'84.68%'},ramenShops:[]},
 {id:'yotugi',name:'四ツ木',position:{top:'26.39%',left:'84.68%' },ramenShops:[]},
 {id:'keiseitateisi',name:'京成立石',position:{top:'24.49%',left:'84.68%'},ramenShops:[]},
 {id:'aoto',name:'青砥',position:{top:'19.45%',left:'84.67%'},ramenShops:[]},
 {id:'keiseihatiman',name:'京成八幡',position:{top:'40.59%',left:'94.45%'},ramenShops:[]},
 {id:'sugano',name:'菅野',position:{top:'38.17%',left:'93.17%'},ramenShops:[]},
 {id:'itikawamama',name:'市川真間',position:{top:'33.50%',left:'93.17%'},ramenShops:[]},
 {id:'kokuhudai',name:'国府台',position:{top:'29.05%',left:'93.17%'},ramenShops:[]},
 {id:'edogawa',name:'江戸川',position:{top:'24.42%',left:'93.17%'},ramenShops:[]},
 {id:'ohanajaya',name:'お花茶屋',position:{top:'20.02%',left:'83.64%'},ramenShops:[]},
 {id:'horikirisyoubuen',name:'堀切菖蒲園',position:{top:'20.10%',left:'82.47%'},ramenShops:[]},
 {id:'keiseisekiya',name:'京成関屋',position:{top:'21.63%',left:'78.99%'},ramenShops:[]},
 {id:'senjuoohasi',name:'千住大橋',position:{top:'19.93%',left:'73.65%'},ramenShops:[]},
 {id:'sinmikawajima',name:'新三河島',position:{top:'22.40%',left:'65.54%'},ramenShops:[]},
 {id:'mikawajima',name:'三河島',position:{top:'27.56%',left:'68.42%'},ramenShops:[]},
 {id:'sintomityo',name:'新富町',position:{top:'65.54%',left:'72.68%'},ramenShops:[]},
 {id:'kojimati',name:'麹町',position:{top:'49.52%',left:'47.10%'},ramenShops:[]},
 {id:'hikawadai',name:'氷川台',position:{top:'11.66%',left:'18.61%'},ramenShops:[]},
 {id:'heiwadai',name:'平和台',position:{top:'7.87%',left:'15.91%'},ramenShops:[]},
 {id:'tikatetuakatuka',name:'地下鉄赤塚',position:{top:'6.89%',left:'12.18%'},ramenShops:[]},
 {id:'tikatetunarimasu',name:'地下鉄成増',position:{top:'7.02%',left:'10.07%'},ramenShops:[]},
 {id:'narimasu',name:'成増',position:{top:'5.57%',left:'10.02%'},ramenShops:[]},
 {id:'simoakatuka',name:'下赤塚',position:{top:'5.69%',left:'13.09%'},ramenShops:[]},
 {id:'tobunerima',name:'東武練馬',position:{top:'12.27%',left:'20.15%' },ramenShops:[]},
 {id:'kamiitabasi',name:'上板橋',position:{top:'14.16%',left:'21.51%' },ramenShops:[]},
 {id:'tokiwadai',name:'ときわ台',position:{top:'14.89%',left:'24.36%' },ramenShops:[]},
 {id:'nakaitabasi',name:'中板橋',position:{top:'14.89%',left:'27.41%' },ramenShops:[]},
 {id:'kitaikebukuro',name:'北池袋',position:{top:'23.45%',left:'33.47%' },ramenShops:[]},
 {id:'simoitabasi',name:'下板橋',position:{top:'19.61%',left:'32.70%' },ramenShops:[]},
 {id:'oyama',name:'大山',position:{top:'15.94%',left:'30.02%' },ramenShops:[]},
 {id:'siinamati',name:'椎名町',position:{top:'23.36%',left:'26.66%' },ramenShops:[]},
 {id:'higasinagasaki',name:'東長崎',position:{top:'21.71%',left:'25.55%' },ramenShops:[]},
 {id:'sakuradai',name:'桜台',position:{top:'20.86%',left:'22.88%' },ramenShops:[]},
 {id:'sinsakuradai',name:'新桜台',position:{top:'17.88%',left:'21.23%' },ramenShops:[]},
 {id:'nakamurabasi',name:'中村橋',position:{top:'20.90%',left:'13.55%' },ramenShops:[]},
 {id:'hujimidai',name:'富士見台',position:{top:'20.90%',left:'12.27%' },ramenShops:[]},
 {id:'nerimatakanodai',name:'練馬高野台',position:{top:'20.90%',left:'10.99%' },ramenShops:[]},
 {id:'syakujikouen',name:'石神井公園',position:{top:'20.90%',left:'9.70%' },ramenShops:[]},
 {id:'ooizumigakuen',name:'大泉学園',position:{top:'20.90%',left:'8.45%' },ramenShops:[]},
 {id:'hoya',name:'保谷',position:{top:'20.90%',left:'7.17%' },ramenShops:[]},
 {id:'higasikurume',name:'東久留米',position:{top:'20.90%',left:'4.64%' },ramenShops:[]},
 {id:'kamisyakujii',name:'上石神井',position:{top:'27.52%',left:'5.89%' },ramenShops:[]},
 {id:'kamiigusa',name:'上井草',position:{top:'27.52%',left:'7.09%' },ramenShops:[]},
 {id:'ihagi',name:'井萩',position:{top:'27.52%',left:'8.28%' },ramenShops:[]},
 {id:'simoigusa',name:'下井草',position:{top:'27.52%',left:'9.45%' },ramenShops:[]},
 {id:'saginomiya',name:'鷺ノ宮',position:{top:'27.52%',left:'10.64%' },ramenShops:[]},
 {id:'toritukasei',name:'都立家政',position:{top:'27.52%',left:'11.78%' },ramenShops:[]},
 {id:'nokata',name:'野方',position:{top:'27.52%',left:'12.98%' },ramenShops:[]},
 {id:'numabukuro',name:'沼袋',position:{top:'27.52%',left:'14.17%' },ramenShops:[]},
 {id:'araiyakusimae',name:'新井薬師前',position:{top:'27.52%',left:'15.34%' },ramenShops:[]},
 {id:'nakai',name:'中井',position:{top:'27.52%',left:'17.76%' },ramenShops:[]},
 {id:'simootiai',name:'下落合',position:{top:'29.10%',left:'22.68%' },ramenShops:[]},
 {id:'otiai',name:'落合',position:{top:'30.63%',left:'19.04%' },ramenShops:[]},
 {id:'okubo',name:'大久保',position:{top:'33.94%',left:'21.34%' },ramenShops:[]},
 {id:'sendagaya',name:'千駄ヶ谷',position:{top:'48.09%',left:'32.98%' },ramenShops:[]},
 {id:'sinanomati',name:'信濃町',position:{top:'48.05%',left:'37.08%' },ramenShops:[]},
 {id:'kameido',name:'亀戸',position:{top:'41.93%',left:'87.99%' },ramenShops:[]},
 {id:'hirai',name:'平井',position:{top:'43.06%',left:'89.44%' },ramenShops:[]},
 {id:'sinkoiwa',name:'新小岩',position:{top:'43.10%',left:'90.43%' },ramenShops:[]},
 {id:'koiwa',name:'小岩',position:{top:'43.10%',left:'91.41%' },ramenShops:[]},
 {id:'itikawa',name:'市川',position:{top:'43.10%',left:'92.43%' },ramenShops:[]},
 {id:'simousanakayama',name:'下総中山',position:{top:'52.42%',left:'93.86%' },ramenShops:[]},
 {id:'genbokunakayama',name:'原木中山',position:{top:'55.81%',left:'93.97%' },ramenShops:[]},
 {id:'minamigyoutoku',name:'南行徳',position:{top:'55.81%',left:'90.30%' },ramenShops:[]},
 {id:'nisikasai',name:'西葛西',position:{top:'55.81%',left:'86.66%' },ramenShops:[]},
 {id:'minamisunamati',name:'南砂町',position:{top:'55.81%',left:'85.43%' },ramenShops:[]},
 {id:'toyotyo',name:'東陽町',position:{top:'55.89%',left:'84.24%' },ramenShops:[]},
 {id:'kiba',name:'木場',position:{top:'55.81%',left:'83.04%' },ramenShops:[]},
 {id:'mitakadai',name:'三鷹台',position:{top:'37.65%',left:'8.88%' },ramenShops:[]},
 {id:'hujimigaoka',name:'富士見ヶ丘',position:{top:'40.52%',left:'10.87%' },ramenShops:[]},
 {id:'hamadayama',name:'浜田山',position:{top:'43.14%',left:'12.75%' },ramenShops:[]},
 {id:'nisieihuku',name:'西永福',position:{top:'44.55%',left:'13.75%' },ramenShops:[]},
 {id:'eihukutyo',name:'永福町',position:{top:'45.76%',left:'14.59%' },ramenShops:[]},
 {id:'higasimatubara',name:'東松原',position:{top:'50.36%',left:'15.91%' },ramenShops:[]},
 {id:'sindaita',name:'新代田',position:{top:'52.80%',left:'15.91%' },ramenShops:[]},
 {id:'ikenoue',name:'池ノ上',position:{top:'58.39%',left:'17.59%' },ramenShops:[]},
 {id:'komabatodaimae',name:'駒場東大前',position:{top:'59.28%',left:'23.19%' },ramenShops:[]},
 {id:'sinsen',name:'神泉',position:{top:'59.28%',left:'27.29%' },ramenShops:[]},
 {id:'ikejiriohasi',name:'池尻大橋',position:{top:'59.93%',left:'25.50%' },ramenShops:[]},
 {id:'sangendyaya',name:'三軒茶屋',position:{top:'64.93%',left:'21.12%' },ramenShops:[]},
 {id:'komazawadaigaku',name:'駒澤大学',position:{top:'66.87%',left:'17.64%' },ramenShops:[]},
 {id:'sakurasinmati',name:'桜新町',position:{top:'66.87%',left:'15.68%' },ramenShops:[]},
 {id:'yoga',name:'用賀',position:{top:'66.87%',left:'13.39%' },ramenShops:[]},
 {id:'nisitaisidou',name:'西太子堂',position:{top:'64.85%',left:'19.69%' },ramenShops:[]},
 {id:'wakabayasi',name:'若林',position:{top:'64.85%',left:'18.09%' },ramenShops:[]},
 {id:'syoinjinjamae',name:'松陰神社前',position:{top:'64.85%',left:'16.39%' },ramenShops:[]},
 {id:'setagaya',name:'世田谷',position:{top:'64.85%',left:'14.54%' },ramenShops:[]},
 {id:'kamimati',name:'上町',position:{top:'64.85%',left:'12.50%' },ramenShops:[]},
 {id:'miyanozaka',name:'宮野坂',position:{top:'61.18%',left:'10.16%' },ramenShops:[]},
 {id:'yamasita',name:'山下',position:{top:'52.50%',left:'10.42%' },ramenShops:[]},
 {id:'matubara',name:'松原',position:{top:'50.16%',left:'10.19%' },ramenShops:[]},
 {id:'kitami',name:'喜多見',position:{top:'55.08%',left:'4.52%' },ramenShops:[]},
 {id:'sosigayaookura',name:'祖師ヶ谷大蔵',position:{top:'55.08%',left:'6.86%' },ramenShops:[]},
 {id:'gotokuji',name:'豪徳寺',position:{top:'55.93%',left:'11.10%' },ramenShops:[]},
 {id:'umegaoka',name:'梅が丘',position:{top:'55.08%',left:'12.61%' },ramenShops:[]},
 {id:'higasikitazawa',name:'東北沢',position:{top:'55.00%',left:'18.18%' },ramenShops:[]},
 {id:'yoyogihatiman',name:'代々木八幡',position:{top:'50.97%',left:'22.59%' },ramenShops:[]},
 {id:'sangubasi',name:'参宮橋',position:{top:'46.45%',left:'25.78%' },ramenShops:[]},
 {id:'minamisinjuku',name:'南新宿',position:{top:'44.87%',left:'26.92%' },ramenShops:[]},
 {id:'rokakouen',name:'芦花公園',position:{top:'48.43%',left:'4.99%' },ramenShops:[]},
 {id:'hatimanyama',name:'八幡山',position:{top:'48.47%',left:'6.06%' },ramenShops:[]},
 {id:'kamikitazawa',name:'上北沢',position:{top:'48.47%',left:'7.14%' },ramenShops:[]},
 {id:'daitabasi',name:'代田橋',position:{top:'48.47%',left:'19.15%' },ramenShops:[]},
 {id:'hatudai',name:'初台',position:{top:'45.08%',left:'25.41%' },ramenShops:[]},
 {id:'minamiasagaya',name:'南阿佐ヶ谷',position:{top:'35.55%',left:'9.93%' },ramenShops:[]},
 {id:'sinkouenji',name:'新高円寺',position:{top:'37.04%',left:'11.12%' },ramenShops:[]},
 {id:'higasikouenji',name:'東高円寺',position:{top:'38.90%',left:'13.49%' },ramenShops:[]},
 {id:'sinakano',name:'新中野',position:{top:'38.98%',left:'15.00%' },ramenShops:[]},
 {id:'honantyo',name:'方南町',position:{top:'44.11%',left:'16.16%' },ramenShops:[]},
 {id:'nakanohujimityo',name:'中野富士見町',position:{top:'42.29%',left:'16.16%' },ramenShops:[]},
 {id:'nakanosinbasi',name:'中野新橋',position:{top:'40.48%',left:'16.13%' },ramenShops:[]},
 {id:'nisisinjuku',name:'西新宿',position:{top:'38.98%',left:'22.80%' },ramenShops:[]},
 {id:'yotuyasantyome',name:'四谷三丁目',position:{top:'45.19%',left:'38.73%' },ramenShops:[]},
 {id:'akasakamituke',name:'赤坂見附',position:{top:'60.94%',left:'45.79%' },ramenShops:[]},
 {id:'awajityo',name:'淡路町',position:{top:'52.95%',left:'59.48%' },ramenShops:[]},
 {id:'omotesando',name:'表参道',position:{top:'59.64%',left:'35.37%' },ramenShops:[]},
 {id:'aoyamaityoume',name:'青山一丁目',position:{top:'60.50%',left:'40.69%' },ramenShops:[]},
 {id:'hanzomon',name:'半蔵門',position:{top:'50.56%',left:'49.03%' },ramenShops:[]},
 {id:'toranomon',name:'虎ノ門',position:{top:'65.82%',left:'54.50%' },ramenShops:[]},
 {id:'uenohirokouji',name:'上野広小路',position:{top:'40.72%',left:'60.05%' },ramenShops:[]},
 {id:'inarimati',name:'稲荷町',position:{top:'33.50%',left:'69.41%' },ramenShops:[]},
 {id:'omorikaigan',name:'大森海岸',position:{top:'93.87%',left:'51.17%' },ramenShops:[]},
 {id:'tatiaigawa',name:'立会川',position:{top:'92.45%',left:'51.17%' },ramenShops:[]},
 {id:'samesu',name:'鮫洲',position:{top:'90.88%',left:'51.17%' },ramenShops:[]},
 {id:'aomonoyokotyo',name:'青物横丁',position:{top:'88.29%',left:'51.17%' },ramenShops:[]},
 {id:'sinbaba',name:'新馬場',position:{top:'86.56%',left:'51.17%' },ramenShops:[]},
 {id:'kitasinagawa',name:'北品川',position:{top:'84.83%',left:'51.17%' },ramenShops:[]},
 {id:'tukijisijo',name:'築地市場',position:{top:'71.27%',left:'71.89%' },ramenShops:[]},
 {id:'kasairinkaikoen',name:'葛西臨海公園',position:{top:'63.16%',left:'86.91%' },ramenShops:[]},
 {id:'siomi',name:'潮見',position:{top:'63.56%',left:'83.24%' },ramenShops:[]},
 {id:'etyuujima',name:'越中島',position:{top:'63.56%',left:'80.99%' },ramenShops:[]},
 {id:'akebonobasi',name:'曙橋',position:{top:'40.92%',left:'40.64%' },ramenShops:[]},
 {id:'iwamototyo',name:'岩本町',position:{top:'47.98%',left:'66.56%' },ramenShops:[]},
 {id:'bakuroyokoyama',name:'馬喰横山',position:{top:'47.25%',left:'73.28%' },ramenShops:[]},
 {id:'hamatyo',name:'浜町',position:{top:'47.86%',left:'77.58%' },ramenShops:[]},
 {id:'nisitakasimadaira',name:'西高島平',position:{top:'6.38%',left:'23.96%' },ramenShops:[]},
 {id:'sintakasimadaira',name:'新高島平',position:{top:'6.38%',left:'25.87%' },ramenShops:[]},
 {id:'takasimadaira',name:'高島平',position:{top:'6.38%',left:'27.35%' },ramenShops:[]},
 {id:'nisidai',name:'西台',position:{top:'6.38%',left:'28.46%' },ramenShops:[]},
 {id:'hasune',name:'蓮根',position:{top:'6.38%',left:'29.96%' },ramenShops:[]},
 {id:'simurasantyome',name:'志村三丁目',position:{top:'6.38%',left:'31.13%' },ramenShops:[]},
 {id:'simurasakaue',name:'志村坂上',position:{top:'8.15%',left:'32.33%' },ramenShops:[]},
 {id:'motohasunuma',name:'本蓮沼',position:{top:'9.40%',left:'33.24%' },ramenShops:[]},
 {id:'itabasikuyakusyomae',name:'板橋区役所前',position:{top:'11.91%',left:'35.09%' },ramenShops:[]},
 {id:'nisisugamo',name:'西巣鴨',position:{top:'14.33%',left:'40.01%' },ramenShops:[]},
 {id:'sengoku',name:'千石',position:{top:'23.96%',left:'47.87%' },ramenShops:[]},
 {id:'sirayama',name:'白山',position:{top:'25.10%',left:'47.87%' },ramenShops:[]},
 {id:'hibiya',name:'日比谷',position:{top:'60.81%',left:'57.43%' },ramenShops:[]},
 {id:'hiro',name:'広尾',position:{top:'67.11%',left:'37.56%' },ramenShops:[]},
 {id:'iriya',name:'入谷',position:{top:'30.39%',left:'69.99%' },ramenShops:[]},
 {id:'kitaayase',name:'北綾瀬',position:{top:'10.82%', left: '80.02%' }, ramenShops:[]},
 {id:'ayase',name:'綾瀬',position:{top:'12.23%', left: '78.32%' }, ramenShops:[]},
 {id:'sendagi',name:'千駄木',position:{top:'29.74%', left: '57.68%' }, ramenShops:[]},
 {id:'yoyogikoekn',name:'代々木公園',position:{top:'53.75%', left: '26.86%' }, ramenShops:[]},
 {id:'kitasando',name:'北参道',position:{top:'51.98%', left: '35.77%' }, ramenShops:[]},
 {id:'hikarigaoka',name:'光が丘',position:{top:'13.52%', left: '15.51%' }, ramenShops:[]},
 {id:'nerimakasugatyou',name:'練馬春日町',position:{top:'14.85%', left: '16.45%' }, ramenShops:[]},
 {id:'tosimaen',name:'豊島園',position:{top:'16.55%', left: '17.33%' }, ramenShops:[]},
 {id:'sinegota',name:'新江古田',position:{top:'22.64%', left: '17.70%' }, ramenShops:[]},
 {id:'otiaihigasinagasaki',name:'落合東長崎',position:{top:'25.54%', left: '17.70%' }, ramenShops:[]},
 {id:'uenookatimati',name:'上野御徒町',position:{top:'37.41%', left: '60.88%' }, ramenShops:[]},
 {id:'sinokatimati',name:'新御徒町',position:{top:'36.68%', left: '70.02%' }, ramenShops:[]},
 {id:'kokuritukyougijou',name:'国立競技場',position:{top:'52.90%', left: '37.36%' }, ramenShops:[]},
 {id:'jujo',name:'十条',position:{top:'11.58%', left: '37.96%' }, ramenShops:[]},
 {id:'ogu',name:'尾久',position:{top:'16.55%', left: '55.41%' }, ramenShops:[]},
 {id:'kyodo',name:'経堂',position:{top:'55.00%', left: '9.20%' }, ramenShops:[]},
 {id:'simo',name:'志茂',position:{top:'9.20%', left: '46.99%' }, ramenShops:[]},
 {id:'nisigahara',name:'西ヶ原',position:{top:'12.63%', left: '53.24%' }, ramenShops:[]},
 {id:'honkomagome',name:'本駒込',position:{top:'24.29%', left: '53.29%' }, ramenShops:[]},
 {id:'todaimae',name:'東大前',position:{top:'26.07%', left: '53.29%' }, ramenShops:[]},
 {id:'kameidosuijin',name:'亀戸水神',position:{top:'36.68%', left:'87.99%'}, ramenShops:[]},
 {id:'higasiazuma',name:'東あずま',position:{top:'33.25%', left:'86.99%'}, ramenShops:[]},
 {id:'komurai',name:'小村井',position:{top:'33.01%', left:'85.77%'}, ramenShops:[]},
 {id:'hunabiki',name:'船曳',position:{top:'32.97%', left:'81.63%'}, ramenShops:[]},
 {id:'kanigahuti',name:'鐘ヶ淵',position:{top:'26.03%', left:'81.76%'}, ramenShops:[]},
 {id:'horikiri',name:'堀切',position:{top:'22.72%', left:'81.73%'}, ramenShops:[]},
 {id:'usita',name:'牛田',position:{top:'17.98%', left:'78.91%'}, ramenShops:[]},
 {id:'kosuga',name:'小菅',position:{top:'14.00%', left:'76.70%'}, ramenShops:[]},
 {id:'gotanno',name:'五反野',position:{top:'12.63%', left:'73.59%'}, ramenShops:[]},
 {id:'umejima',name:'梅島',position:{top:'11.58%', left:'72.79%'}, ramenShops:[]},
 {id:'nisiarai',name:'西新井',position:{top:'8.88%', left:'71.06%'}, ramenShops:[]},
 {id:'daisimae',name:'大師前',position:{top:'7.06%', left:'68.53%'}, ramenShops:[]},
 {id:'takenotuka',name:'竹ノ塚',position:{top:'7.63%', left:'71.03%'}, ramenShops:[]},
 {id:'tanituka',name:'谷塚',position:{top:'6.22%', left:'71.06%'}, ramenShops:[]},
 {id:'souka',name:'草加',position:{top:'4.64%', left:'71.09%'}, ramenShops:[]},
 {id:'sibamata',name:'柴又',position:{top:'17.19%', left:'87.51%'}, ramenShops:[]},
 {id:'kanemati',name:'金町（京成金町）',position:{top:'13.68%', left:'85.97%'}, ramenShops:[]},
 {id:'kameari',name:'亀有',position:{top:'12.63%', left:'83.84%' }, ramenShops:[]},
 {id:'sijoumae',name:'市場前',position:{top:'79.18%',left:'81.93%'}, ramenShops:[]},
 {id:'ariaketenisunomori',name:'有明テニスの森',position:{top:'81.40%',left:'80.80%'}, ramenShops:[]},
 {id:'kokusaitenjijoumae',name:'国際展示場前',position:{top:'84.38%',left:'78.50%'}, ramenShops:[]},
 {id:'oumi',name:'青海',position:{top:'84.54%',left:'77.38%'}, ramenShops:[]},
 {id:'terekomusenta-',name:'テレコムセンター',position:{top:'84.54%',left:'76.09%'}, ramenShops:[]},
 {id:'hunenokagakukan',name:'船の科学館',position:{top:'84.50%',left:'74.90%'}, ramenShops:[]},
 {id:'daiba',name:'台場',position:{top:'81.40%',left:'71.74%'}, ramenShops:[]},
 {id:'waseda-toden',name:'早稲田（都電）',position:{top:'33.30%',left:'38.59%'}, ramenShops:[]},
 {id:'omokagebasi',name:'面影橋',position:{top:'31.76%',left:'37.56%'}, ramenShops:[]},
 {id:'gakusyuinsita',name:'学習院下',position:{top:'30.18%',left:'37.59%'}, ramenShops:[]},
 {id:'tukumogamimae',name:'鬼子母神前',position:{top:'28.77%',left:'39.05%'}, ramenShops:[]},
 {id:'todenzousigaya',name:'都電雑司ヶ谷',position:{top:'27.44%',left:'37.56%'}, ramenShops:[]},
 {id:'mukoubara',name:'向原',position:{top:'23.61%',left:'40.00%'}, ramenShops:[]},
 {id:'sigasiikebukuroyontyo-me',name:'東池袋四丁目',position:{top:'25.58%',left:'39.70%'}, ramenShops:[]},
 {id:'sugamosinden',name:'巣鴨新田',position:{top:'18.56%',left:'42.79%'}, ramenShops:[]},
 {id:'kosinduka',name:'庚申塚',position:{top:'17.27%',left:'42.76%'}, ramenShops:[]},
 {id:'sinkosinduka',name:'新庚申塚',position:{top:'16.22%',left:'42.76%'}, ramenShops:[]},
 {id:'nisigararayontyome',name:'西ヶ原四丁目',position:{top:'14.73%',left:'45.05%'}, ramenShops:[]},
 {id:'sakaemati',name:'栄町',position:{top:'8.03%',left:'53.19%'}, ramenShops:[]},
 {id:'kajiwara',name:'梶原',position:{top:'8.07%',left:'54.21%'}, ramenShops:[]},
 {id:'arakawasyakomae',name:'荒川車庫前',position:{top:'9.64%',left:'55.51%'}, ramenShops:[]},
 {id:'arakawayuentimae',name:'荒川遊園地前',position:{top:'11.46%',left:'56.86%'}, ramenShops:[]},
 {id:'odai',name:'小台',position:{top:'12.55%',left:'57.57%'}, ramenShops:[]},
 {id:'miyanomae',name:'宮ノ前',position:{top:'13.96%',left:'58.60%'}, ramenShops:[]},
 {id:'kumanomae',name:'熊野前',position:{top:'14.81%',left:'61.41%'}, ramenShops:[]},
 {id:'higasiogusantyome',name:'東尾久三丁目',position:{top:'14.90%',left:'65.76%'}, ramenShops:[]},
 {id:'matiyanityome',name:'町屋二丁目',position:{top:'14.90%',left:'69.13%'}, ramenShops:[]},
 {id:'arakawananatyome',name:'荒川七丁目',position:{top:'19.93%',left:'72.06%'}, ramenShops:[]},
 {id:'arakawanityome',name:'荒川二丁目',position:{top:'21.43%',left:'72.06%' }, ramenShops:[]},
 {id:'arakawaityumae',name:'荒川一中前',position:{top:'24.50%',left:'72.06%' }, ramenShops:[]},
 {id:'minowabasi',name:'三ノ輪橋',position:{top:'25.91%',left:'72.06%' }, ramenShops:[]},
 {id:'uguisudani',name:'鶯谷',position:{top:'30.75%',left:'63.77%' }, ramenShops:[]},
 {id:'nisiarakawataisinisi',name:'西荒川大師西',position:{top:'6.78%',left:'61.18%' }, ramenShops:[]},
 {id:'ekita',name:'江北',position:{top:'8.20%',left:'61.18%' }, ramenShops:[]},
 {id:'takano',name:'高野',position:{top:'9.73%',left:'61.18%' }, ramenShops:[]},
 {id:'ougioohasi',name:'扇大橋',position:{top:'11.22%',left:'61.18%' }, ramenShops:[]},
 {id:'adatiodai',name:'足立小台',position:{top:'12.75%',left:'61.22%' }, ramenShops:[]},
 {id:'akatutisyogakkoumae',name:'赤土小学校前',position:{top:'16.55%',left:'61.15%' }, ramenShops:[]},
 {id:'sinonome',name:'東雲',position:{top:'78.05%',left:'85.12%' }, ramenShops:[]},
 {id:'sinagawasi-saido',name:'品川シーサイド',position:{top:'87.45%',left:'55.37%' }, ramenShops:[]},
 {id:'ooikeibajoumae',name:'大井競馬場前',position:{top:'84.87%',left:'57.46%' }, ramenShops:[]},
 {id:'ryutu-senta-',name:'流通センター',position:{top:'86.19%',left:'57.49%' }, ramenShops:[]},
 {id:'syowajima',name:'昭和島',position:{top:'87.37%',left:'57.49%' }, ramenShops:[]},
 {id:'seibijo',name:'整備場',position:{top:'88.50%',left:'57.49%' }, ramenShops:[]},
 {id:'tenkubasi',name:'天空橋',position:{top:'91.81%',left:'57.49%' }, ramenShops:[]},
 {id:'takinogawaittyoume',name:'滝野川一丁目',position:{top:'12.83%',left:'49.37%' }, ramenShops:[]},
 {id:'nisikoyama',name:'西小山',position:{top:'73.69%',left:'27.72%' }, ramenShops:[]},
 {id:'okusawa',name:'奥沢',position:{top:'79.38%',left:'20.55%' }, ramenShops:[]},

{id:'kikukawa',name:'菊川',position:{top:'47.90%',left:'80.79%'},ramenShops:[]},
{id:'morisita',name:'森下',position:{top:'47.90%',left:'79.52%'},ramenShops:[]},
{id:'bakurotyo',name:'馬喰町',position:{top:'46.04%',left:'70.89%'},ramenShops:[]},
{id:'kiyosumisirakawa',name:'清澄白河',position:{top:'54.68%',left:'80.05%'},ramenShops:[]},
{id:'tukisima',name:'月島',position:{top:'66.87%',left:'79.43%'},ramenShops:[]},
{id:'minowa',name:'三ノ輪',position:{top:'30.59%',left:'72.74%'},ramenShops:[]},
{id:'akabaneiwabuti',name:'赤羽岩淵',position:{top:'7.18%',left:'45.82%'},ramenShops:[]},
{id:'oimati',name:'大井町',position:{top:'88.50%',left:'47.07%'},ramenShops:[]},
{id:'tennousuairu',name:'天王洲アイル',position:{top:'82.90%',left:'59.31%'},ramenShops:[]},
{id:'toukyouterepo-to',name:'東京テレポート',position:{top:'82.81%',left:'75.75%'},ramenShops:[]},
{id:'sibaurahutou',name:'芝浦ふ頭',position:{top:'75.42%',left:'66.56%'},ramenShops:[]},
{id:'hinode',name:'日の出',position:{top:'73.69%',left:'66.56%'},ramenShops:[]},
{id:'takesiba',name:'竹芝',position:{top:'71.96%',left:'66.56%'},ramenShops:[]},
{id:'ogawamati',name:'小川町',position:{top:'49.60%',left:'59.79%'},ramenShops:[]},
{id:'sinotyanomizu',name:'新御茶ノ水',position:{top:'48.43%',left:'56.37%'},ramenShops:[]},
{id:'yusima',name:'湯島',position:{top:'39.95%',left:'57.68%'},ramenShops:[]},
{id:'nedu',name:'根津',position:{top:'31.88%',left:'57.74%'},ramenShops:[]},
{id:'usigomekagurazaka',name:'牛込神楽坂',position:{top:'37.37%',left:'45.69%'},ramenShops:[]},
{id:'usigomeyanagimati',name:'牛込柳町',position:{top:'37.37%',left:'41.72%'},ramenShops:[]},
{id:'wakamatukawata',name:'若松河田',position:{top:'37.37%',left:'38.33%'},ramenShops:[]},
{id:'sintoyosu',name:'新豊洲',position:{top:'75.34%',left:'81.90%'},ramenShops:[]},
{ id: 'nisihunabasi', name: '西船橋', position: { top: '55.81%', left: '95.65%' }, ramenShops: [] },
{id:'',name:'',position:{top:'px',left:'px'},ramenShops:[]},
{id:'',name:'',position:{top:'px',left:'px'},ramenShops:[]},
{id:'',name:'',position:{top:'px',left:'px'},ramenShops:[]},
{id:'',name:'',position:{top:'px',left:'px'},ramenShops:[]},
{id:'',name:'',position:{top:'px',left:'px'},ramenShops:[]},
{id:'',name:'',position:{top:'px',left:'px'},ramenShops:[]},
{id:'',name:'',position:{top:'px',left:'px'},ramenShops:[]},
{id:'',name:'',position:{top:'px',left:'px'},ramenShops:[]},
{id:'',name:'',position:{top:'px',left:'px'},ramenShops:[]},
{id:'',name:'',position:{top:'px',left:'px'},ramenShops:[]},





];



// アプリのメインの部分。ここに書かれた内容がウェブサイトに表示されます。
function App() {
  // `selectedStation` は、今、どの駅のラーメン情報が表示されているかを記憶する箱です。
  // `setSelectedStation` は、その箱の中身を変更するための命令です。
  // 最初は何も表示されていないので `null`（空っぽ）です。
  const [selectedStation, setSelectedStation] = React.useState(null);

  // 駅のボタンがクリックされたときに動く命令です。
  // クリックされた駅の情報を `selectedStation` に記憶させます。
  const handleStationClick = (station) => {
    setSelectedStation(station);
  };

  // ラーメン情報が表示されているポップアップ（モーダル）の「閉じる」ボタンがクリックされたときに動く命令です。
  // `selectedStation` を空っぽにして、ポップアップを閉じます。
  const handleCloseModal = () => {
    setSelectedStation(null);
  };

  return (
    // アプリ全体の入れ物となる一番外側の箱
    <div className="App">
      {/* 路線図を表示するエリア。CSSで背景画像を設定します。 */}
      <div className="map-container">
        {/* この img タグは、CSSで背景画像を設定するためにも必要です。 */}
        <img src={lineImage} alt="東京路線図" className="line-map-image" />

        {/*
          stationDataの各駅の情報を使って、一つずつボタンを作ります。
          map() は、リストの項目を一つずつ取り出して何かをするための命令です。
        */}
        {stationData.map((station) => (
          // 駅のボタン
          <button
            key={station.id} // それぞれのボタンを区別するための名前（重要！）
            className="station-button" // CSSで見た目を設定するための名前
            // ボタンの位置を、stationDataで設定したtopとleftに合わせて決めます
            style={{ top: station.position.top, left: station.position.left }}
            // このボタンがクリックされたら、handleStationClickの命令を実行します
            onClick={() => handleStationClick(station)}
          >
            {station.name} {/* ボタンに表示される駅の名前 */}
          </button>
        ))}
      </div>

      {/*
        ラーメン屋さんの情報が表示されるポップアップ（モーダル）の部分。
        `selectedStation && (...)` は、「もしselectedStationに何か情報が入っていたら(...)の中身を表示する」という意味です。
        つまり、駅のボタンがクリックされた時だけ表示されます。
      */}
      {selectedStation && (
        <div className="modal-overlay"> {/* ポップアップの背景（半透明の黒い部分） */}
          <div className="modal-content"> {/* ポップアップの中身 */}
            <h2>{selectedStation.name} のラーメン屋さん</h2> {/* クリックされた駅の名前を表示 */}
            {selectedStation.ramenShops.length > 0 ? ( // ラーメン情報がある場合
              <ul> {/* ラーメン屋さんのリスト */}
                {/*
                  選択された駅のramenShops（ラーメン屋さんリスト）を一つずつ取り出して表示します。
                */}
                {selectedStation.ramenShops.map((shop, index) => (
                  <li key={index}> {/* リストの項目一つ一つ */}
                    <h3>{shop.name}</h3> {/* ラーメン屋さんの名前 */}
                    <p>{shop.description}</p> {/* ラーメン屋さんの説明 */}
                    <p>評価: {shop.rating} / 5</p> {/* ラーメン屋さんの評価 */}
                  </li>
                ))}
              </ul>
            ) : ( // ラーメン情報がない場合
              <p>この駅には現在、おすすめのラーメン情報がありません。</p>
            )}
            {/* ポップアップを閉じるボタン */}
            <button onClick={handleCloseModal} className="close-button">閉じる</button>
          </div>
        </div>
      )}
    </div>
  );
}

// このAppコンポーネントを他のファイルでも使えるようにするおまじない
export default App;