// src/App.js

// Reactを使うためのおまじない。アプリの動きを作るのに必要です。
import React from 'react';
// このJSファイルに対応する見た目の設定ファイル（App.css）を読み込みます。
import './App.css';
// 同じフォルダにある路線図の画像ファイルを読み込みます。
import lineImage from './line.png'; // ★画像ファイルをここで読み込む

// src/App.js の中、`import './App.css';` のすぐ下あたりに貼り付けてください。

// src/App.js の中、`import './App.css';` のすぐ下あたりに貼り付けてください。

// ----------------------------------------------------
// ★ここからが、あなたのアプリに表示される駅とラーメン屋さんの情報です★
// ここに駅やラーメン屋さんの情報を追加・編集していきます。
const stationData = [
  // --- 山手線主要駅 ---
 {
    id: 'tokyo',
    name: '東京',
    position: { top: '59.08%', left: '64.74%' },
    ramenShops: [],
  },
  {
    id: 'shinjuku',
    name: '新宿',
    position: { top: '41.36%', left: '30.17%' },
    ramenShops: [{name:'麺屋　翔　本店',description:'インパクトにはやや欠けるものの綺麗なラーメンという印象。欠点という欠点がない優等生な一杯。',rating:3.78},{ name:'ラーメン二郎　新宿小滝橋通り店',description:'直系二郎の中でも一味違った一杯。好みが別れると思う。',rating:3.57},{name:'ラーメン二郎　歌舞伎町店',description:'NS系の二郎。テボでゆでられた麺、乳化したスープが特徴。他の店と比べると夜遅くまで営業している。',rating:3.66},],
  },
  {
    id: 'shibuya',
    name: '渋谷',
    position: { top: '59.72%', left: '30.73%' },
    ramenShops: [{ name:'蒙古タンメン中本　渋谷店',description:'渋谷駅直結の蒙古タンメン。しびれるほどの辛さだが、ニンニクのパンチもありウマ辛な仕様になっている。一回は食べてほしい。',rating:3.48},{ name:'らーめん　穀雨',description:'渋谷駅の離れにたたずむ「かづ屋」出身の名店。優しい口当たりのスープに別皿の揚げネギを加えればコクが増しておいしい。',rating:3.70},{ name:'黄金の塩らぁ麺　ドゥエ　イタリアン　東急プラザ渋谷店',description:'塩ラーメンにチーズがかかった新感覚ラーメン。意外にもチーズがおいしさを引き立て、癖になる味わい。〆のご飯を投入して最後まで楽しめる',rating:3.49},{ name:'麺屋武蔵　武骨外伝',description:'魚介豚骨のスープともちもち麺がマッチ。チャーシューがとんでもなくごっつい。',rating:3.42},{ name: 'はやし', description: '魚介豚骨のシンプルながら奥深い一杯。', rating: 3.78 }],
  },
  {
    id: 'ikebukuro',
    name: '池袋',
    position: { top: '25.83%', left: '33.15%' },
    ramenShops: [{name:'味噌麺処　田坂屋',description:'花道系。ベジポタのような濃厚感に中太麺、ラードが交じり合い最高のコンビネーションを魅せる。通し営業であることもうれしい。',rating:3.74},{name:'皇綱家',description:'輝道家で修業した店主の店。スモーキーなチャーシュー、インパクトの強いスープが最高。他の家系よりも醤油感強め？',rating:3.70},{name:'宍道湖しじみ中華蕎麦　琥珀　池袋店',description:'滋味深いシジミの味が前に出た一杯。動物系ではないのでパンチはないが、落ち着いた味を楽しめる。',rating:3.72},{ name:'ラーメン二郎　池袋東口店',description:'NS系のラーメン二郎。微乳化でマイルドなことが特徴。カラメをコールすることをおすすめしたい。',rating:3.64},{ name:'麺処　花田　池袋店',description:'花道系味噌ラーメン。ベジポタのような濃厚スープに煮込まれた野菜がおいしい。',rating:3.74},{ name:'鶏の穴',description:'池袋の隠れた名店。鶏白湯の濃厚スープに中太麺が絡んでおいしい。鶏チャーも香高く、都内有数の鶏白湯を楽しめる。',rating:3.62},{ name:'ジャパニーズ ラーメン 五感',description:'完全無化調、素材の旨味を存分に楽しめる一杯',rating:3.97},{ name:'むかん　池袋',description:'魚介感たっぷりの牡蠣塩ラーメンを安価で食べられる。いつでも安定したおいしさを楽しめる。',rating:3.50},{ name:'屯ちん　池袋西口店',description:'東京豚骨の店。麺は細麺でスープには醤油感が強い。',rating:3.49}],
  },
  {
    id: 'ueno',
    name: '上野',
    position: { top: '33.86%', left: '65.31%' },
    ramenShops: [{ name:'一蘭　アトレ上野山下口店',description:'癖のない豚骨ラーメン。麺量が少ないので替え玉は必須',rating:3.38}],
  },
  {
    id: 'shinagawa',
    name: '品川',
    position: { top: '82.20%', left: '51.23%' },
    ramenShops: [

    ],
  },
  {
    id: 'ginza',
    name: '銀座',
    position: { top: '64.24%', left: '67.36%' },
    ramenShops: [],
  },
  {
    id: 'akihabara',
    name: '秋葉原',
    position: { top: '42.98%', left: '64.91%' },
    ramenShops: [{ name:'麺処　ほん田　秋葉原本店',description:'魚介の風味が漂うスープをツルツルの麺に絡めてすすればとんでもなくおいしい。王道を往く醤油ラーメン。',rating:3.77},],
  },
  {
    id: 'yurakucho',
    name: '有楽町',
    position: { top: '61.70%', left: '63.21%' },
    ramenShops: [],
  },
  {
    id: 'shimbashi',
    name: '新橋',
    position: { top: '66.30%', left: '64.51%' },
    ramenShops: [],
  },
  {
    id: 'hamamatsucho',
    name: '浜松町',
    position: { top: '74.33%', left: '57.49%' },
    ramenShops: [{ name:'MENクライ',description:'もちもち触感の麺に甘辛いタレが絡み、餅を食べているかのような一杯。',rating:3.75},],
  },
  {
    id: 'tamachi',
    name: '田町(三田)',
    position: { top: '75.34%', left: '55.09%' },
    ramenShops: [{name:'ラーメン二郎　三田本店',description:'非乳化で朝から営業している二郎の原点。麺は柔らかめなので固めを注文することを進めたい。',rating:3.77},],
  },
  {
    id: 'gotanda',
    name: '五反田',
    position: { top: '77.92%', left: '36.99%' },
    ramenShops: [],
  },
  {
    id: 'meguro',
    name: '目黒',
    position: { top: '73.81%', left: '34.40%' },
    ramenShops: [{name:'かづ屋',description:'魚介系の出汁が効いたあっさりラーメン。麺ものど越しがよく抵抗感なく食べられる。',rating:3.76},{ name:'ラーメン二郎　目黒店',description:'この世で最も安価な非乳化二郎。接客は少し怖いが行く価値はおおいに有り',rating:3.72}],
  },
  {
    id: 'ebisu',
    name: '恵比寿',
    position: { top: '66.99%', left: '31.31%' },
    ramenShops: [{name:'手打 親鶏中華そば 綾川',description:'出汁から鶏油、こりこり触感のチャーシューまで親鳥を使った醤油ベースの一杯。青竹打ちで作られる麺にも注目だ。',rating:3.74},],
  },
  {
    id: 'harajuku',
    name: '原宿(明治神宮前)',
    position: { top: '56.13%', left: '31.31%' },
    ramenShops: [],
  },
  {
    id: 'yoyogi',
    name: '代々木',
    position: { top: '49.23%', left: '30.02%' },
    ramenShops: [],
  },
  {
    id: 'shinjuku-gyoemmae',
    name: '新宿御苑前',
    position: { top: '43.38%', left: '37.45%' },
  ramenShops: [{name:'RAMEN MATSUI',description:'美しすぎるビジュアル、冴えわたる醤油感、ジューシーな鴨チャーすべてが美味しい完成度の高いラーメン。',rating:3.84},{name:'Ramen Afro Beats',description:'鶏白湯スープを最後に泡立てることでさらなる円やかさを実現した一杯。和え玉もあるがスープが少し少ないのが難点。',rating:3.73},{ name:'SOBA　HOUSE金色不如帰　新宿御苑本店',description:'あり得ないくらいに完成度の高い一杯。貝を基調としたスープに自家製の柔らかめのスープがとってもおいしい。',rating:3.78}],
  },
  {
    id: 'yotsuya',
    name: '四ツ谷',
    position: { top: '47.62%', left: '41.55%' },
    ramenShops: [],
  },
  {
    id: 'ichigaya',
    name: '市ヶ谷',
    position: { top: '44.07%', left: '46.00%' },
    ramenShops: [],
  },
  {
    id: 'iidabashi',
    name: '飯田橋',
    position: { top: '38.38%', left: '50.85%' },
    ramenShops: [],
  },
  {
    id: 'suidobashi',
    name: '水道橋',
    position: { top: '41.57%', left: '54.07%' },
    ramenShops: [],
  },
  {
    id: 'ochanomizu',
    name: '御茶ノ水',
    position: { top: '44.35%', left: '56.35%' },
    ramenShops: [],
  },
  {
    id: 'kanda',
    name: '神田',
    position: { top: '51.61%', left: '63.46%' },
    ramenShops: [],
  },
  {
    id: 'nihonbashi',
    name: '日本橋',
    position: { top: '56.10%', left: '73.71%' },
    ramenShops: [],
  },
 { id: 'kyobashi', name: '京橋', position: { top: '57.77%', left: '73.62%' }, ramenShops: [] },
 { id: 'shiodome', name: '汐留', position: { top: '70.02%', left: '66.56%' }, ramenShops: [] },
 { id: 'roppongi', name: '六本木', position: { top: '67.03%', left: '40.75%' }, ramenShops: [{name:'入鹿TOKYO 六本木',description:'東京で最も完成度の高い醤油ラーメンの一つ。一口目から直感する旨味は唯一無二といえるだろう。',rating:3.92},] },
 { id: 'azabujuban', name: '麻布十番', position: { top: '70.02%', left: '47.49%' }, ramenShops: [] },
 { id: 'daimon', name: '大門', position: { top: '69.90%', left: '57.97%' }, ramenShops: [] },
 { id: 'tocho-mae', name: '都庁前', position: { top: '39.91%', left: '24.62%' }, ramenShops: [] },
 { id: 'shin-okubo', name: '新大久保', position: { top: '31.56%', left: '30.34%' }, ramenShops: [] },
 { id: 'nakano', name: '中野', position: { top: '33.25%', left: '13.66%' }, ramenShops: [] },
 { id: 'kichijoji', name: '吉祥寺', position: { top: '33.50%', left: '6.43%' }, ramenShops: [] },
 { id: 'tachikawa', name: '立川', position: { top: '33.50%', left: '1.99%' }, ramenShops: [] },
 { id: 'kunitachi', name: '国立', position: { top: '14.41%', left: '-0.71%' }, ramenShops: [] },
 { id: 'kitasenju', name: '北千住', position: { top: '17.19%', left: '75.70%' }, ramenShops: [] },
 { id: 'nishi-nippori', name: '西日暮里', position: { top: '23.77%', left: '61.27%' }, ramenShops: [{ name:'えどもんど',description:'超有名インスパイア。麺量が多いので注意が必要だが気にすることはないほどおいしい。乳化しているので少しマイルド。',rating:3.73},] },
 { id: 'nippori', name: '日暮里', position: { top: '27.60%', left: '64.54%' }, ramenShops: [{name:'麺酒処　ぶらり',description:'鶏白湯ラーメンを提供している。スープはとろとろしていてサムゲタンを彷彿とさせる。メンマ？が緑色でシャキシャキしている。',rating:3.67},] },
 { id: 'asakusa',name: '浅草',position: { top: '34.46%', left: '76.01%' },ramenShops: [], },
 { id: 'skytree', name: 'とうきょうスカイツリー', position: { top: '34.18%', left: '78.08%' }, ramenShops: [] },
 { id: 'kinshicho', name: '錦糸町', position: { top: '43.30%', left: '82.10%' }, ramenShops: [] },
 { id: 'monzennakacho', name: '門前仲町', position: { top: '56.17%', left: '79.00%' }, ramenShops: [] },
 { id: 'toyosu', name: '豊洲', position: { top: '67.35%', left: '81.90%' }, ramenShops: [] },
 { id: 'shinkiba', name: '新木場', position: { top: '63.03%', left: '84.99%' }, ramenShops: [] },
 { id: 'odaiba', name: 'お台場海浜公園', position: { top: '79.74%', left: '71.74%' }, ramenShops: [] },
 { id: 'ginza-icchome', name: '銀座一丁目', position: { top: '61.91%', left: '68.89%' }, ramenShops: [] },
 { id: 'sakuradamon', name: '桜田門', position: { top: '58.07%', left: '53.70%' }, ramenShops: [] },
 { id: 'kasumigaseki', name: '霞ケ関', position: { top: '62.95%', left: '54.38%' }, ramenShops: [] },
 { id: 'nagatacho', name: '永田町', position: { top: '57.46%', left: '47.49%' }, ramenShops: [] },
{ id: 'ryogoku', name: '両国', position: { top: '42.70%', left: '77.77%' }, ramenShops: [] },
{ id: 'sumiyoshi', name: '住吉', position: { top: '47.86%', left: '82.16%' }, ramenShops: [] },
{ id: 'higashi-ginza', name: '東銀座', position: { top: '67.03%', left: '70.17%' }, ramenShops: [] },
{ id: 'tsukiji', name: '築地', position: { top: '69.05%', left: '72.25%' }, ramenShops: [] },
{ id: 'kayabacho', name: '茅場町', position: { top: '57.38%', left: '76.89%' }, ramenShops: [] },
{ id: 'suitengumae', name: '水天宮前', position: { top: '54.56%', left: '76.55%' }, ramenShops: [] },
{ id: 'ningyocho', name: '人形町', position: { top: '52.70%', left: '74.13%' }, ramenShops: [] },
{ id: 'kodemmacho', name: '小伝馬町', position: { top: '48.99%', left: '70.15%' }, ramenShops: [] },
{ id: 'shin-nihonbashi', name: '新日本橋(三越前)', position: { top: '52.10%', left: '69.95%' }, ramenShops: [] },
{ id: 'jinbocho', name: '神保町', position: { top: '51.05%', left: '53.84%' }, ramenShops: [{name:'ラーメン二郎　神田神保町店',description:'二郎の中でもトップクラスに麺量が多い一杯。微乳化で旨いが、最後に苦しくなることは絶対だろう。',rating:3.73},] },
{ id: 'takebashi', name: '竹橋', position: { top: '54.80%', left: '50.57%' }, ramenShops: [] },
{ id: 'kudanshita', name: '九段下', position: { top: '49.96%', left: '50.65%' }, ramenShops: [] },
{ id: 'hongo-sanchome', name: '本郷三丁目', position: { top: '35.67%', left: '55.23%' }, ramenShops: [{name:'中華蕎麦にし乃',description:'ミシュランビブグルマンにも選ばれた絶品塩ラーメン。出汁間強めでインパクトはないが丁寧さを感じ取れる一杯。',rating:3.79},] },
{ id: 'senkawa', name: '千川', position: { top: '19.01%', left: '27.72%' }, ramenShops: [] },
{ id: 'kotake-mukaihara', name: '小竹向原', position: { top: '16.46%', left: '24.30%' }, ramenShops: [] },
{ id: 'nerima', name: '練馬', position: { top: '20.78%', left: '17.39%' }, ramenShops: [] },
{ id: 'waseda', name: '早稲田', position: { top: '34.26%', left: '41.44%' }, ramenShops: [] },
{ id: 'kagurazaka', name: '神楽坂', position: { top: '34.26%', left: '44.54%' }, ramenShops: [] },
{ id: 'higashi-nakano', name: '東中野', position: { top: '34.18%', left: '17.36%' }, ramenShops: [{name:'かしわぎ',description:'独特の製法で作られたスープは癖が一切なく、歯切れのよい麺とあっさりとしたスープを楽しめる。',rating:3.80},] },
{ id: 'nakano-sakaue', name: '中野坂上', position: { top: '38.01%', left: '18.95%' }, ramenShops: [] },
{ id: 'nishishinjuku-gochome', name: '西新宿五丁目', position: { top: '40.03%', left: '22.28%' }, ramenShops: [{name:'らぁ麺や 嶋',description:'予約必須！旨味のオンパレードともいうべき細部にまで気配りが行き届いた現在のラーメンの最先端を往く一杯。',rating:4.02},] },
{ id: 'hatagaya', name: '幡ヶ谷', position: { top: '46.85%', left: '24.22%' }, ramenShops: [] },
{ id: 'sasazuka', name: '笹塚', position: { top: '47.79%', left: '20.49%' }, ramenShops: [] },
{ id: 'meidaimae', name: '明大前', position: { top: '48.34%', left: '16.22%' }, ramenShops: [{name:'もみじ屋',description:'富士丸系の二郎インスパイア。別皿の味付けアブラが絶品なのでぜひコールしてほしい。',rating:3.62},] },
 { id: 'okachimachi', name: '御徒町', position: { top: '68.44%', left: '56.72%' }, ramenShops: [] },
 { id: 'ryogoku', name: '両国', position: { top: '42.70%', left: '77.77%' }, ramenShops: [] },
 { id: 'sumiyoshi', name: '住吉', position: { top: '47.86%', left: '82.16%' }, ramenShops: [] },
 { id: 'hatchobori', name: '八丁', position: { top: '63.24%', left: '77.18%' }, ramenShops: [] },
 { id: 'kayabacho', name: '茅場町', position: { top: '57.38%', left: '76.89%' }, ramenShops: [] },
 { id: 'suitengumae', name: '水天宮前', position: { top: '54.56%', left: '76.55%' }, ramenShops: [] },
 { id: 'ningyocho', name: '人形町', position: { top: '52.70%', left: '74.13%' }, ramenShops: [] },
 { id: 'kodemmacho', name: '小伝馬町', position: { top: '48.99%', left: '70.15%' }, ramenShops: [] },
 { id: 'shin-nihonbashi', name: '新日本橋(三越前)', position: { top: '52.10%', left: '69.95%' }, ramenShops: [] },
 { id: 'takebashi', name: '竹橋', position: { top: '54.80%', left: '50.57%' }, ramenShops: [] },
 { id: 'kudanshita', name: '九段下', position: { top: '49.96%', left: '50.65%' }, ramenShops: [] },
 { id: 'kasuga', name: '春日', position: { top: '31.40%', left: '54.09%' }, ramenShops: [] },
 { id: 'kotake-mukaihara', name: '小竹向原', position: { top: '16.46%', left: '24.30%' }, ramenShops: [] },
 { id: 'nerima', name: '練馬', position: { top: '20.78%', left: '17.39%' }, ramenShops: [] },
 { id: 'ekoda', name: '江古田', position: { top: '20.90%', left: '24.07%' }, ramenShops: [{name:'麺や金時',description:'店に入った瞬間に感じる山椒の香、ピリ辛のタンタンメン、塩ラーメンも独特な味でここにしかない味を楽しめる。',rating:3.86},] },
 { id: 'takadanobaba', name: '高田馬場', position: { top: '29.66%', left: '28.80%' }, ramenShops: [{name:'ラーメン　池田屋　高田馬場店',description:'ビジュアルから素晴らしいインスパイア系のラーメン。豚の旨味がこれでもかと出ていて値段は張るものの絶対に後悔しない一杯。',rating:3.69},] },
 { id: 'waseda', name: '早稲田', position: { top: '34.26%', left: '41.44%' }, ramenShops: [] },
 { id: 'kagurazaka', name: '神楽坂', position: { top: '34.26%', left: '44.54%' }, ramenShops: [] },
 { id: 'higashi-nakano', name: '東中野', position: { top: '34.18%', left: '17.36%' }, ramenShops: [] },
 { id: 'hatagaya', name: '幡ヶ谷', position: { top: '46.85%', left: '24.22%' }, ramenShops: [] },
 { id: 'sasazuka', name: '笹塚', position: { top: '47.79%', left: '20.49%' }, ramenShops: [] },
 { id: 'meidaimae', name: '明大前', position: { top: '48.34%', left: '16.22%' }, ramenShops: [] },
 { id: 'shimo-kitazawa', name: '下北沢', position: { top: '55.08%', left: '15.93%' }, ramenShops: [{ name:'麺と未来',description:'モチモチとした麺と淡麗スープと極太麺、海老がゴロゴロ入ったワンタンが特徴',rating:3.77}] },
 { id: 'naka-meguro', name: '中目黒', position: { top: '66.91%', left: '26.18%' }, ramenShops: [{name:'手打ち　あさま',description:'七彩出身の店主が織りなす絶品手打ちラーメン。値は張るが食べておくべき一杯。',rating:3.64},{name:'麺や みかん',description:'煮干しベースのあっさりとしたスープにこだわりぬかれた吊るしチャーシューを楽しめるお店。「まるえ中華蕎麦」の系譜を感じる確かな一杯。',rating:3.70},] },
 { id: 'jiyugaoka', name: '自由が丘', position: { top: '75.10%', left: '19.72%' }, ramenShops: [{ name:'塩そば　一榮',description:'ボリューミーでのど越し重視の高加水率の麺、全体的に洒落ていて見栄えの良い一杯。',rating:3.49},{ name:'麺うらた',description:'味付けはいたってシンプルな塩ラーメン。少し物足りなさこそ感じるが味に関しては十分すぎる一杯。',rating:3.58},{ name:'無邪気　自由が丘南口店',description:'見た目は家系だが中身は全く違う、醤油感は弱めのあっさりとした一杯。',rating:3.49}] },
 { id: 'okayama', name: '大岡山', position: { top: '76.39%', left: '24.33%' }, ramenShops: [] },
 { id: 'musashi-kosugi', name: '武蔵小杉', position: { top:'84.14%', left:'11.72%' }, ramenShops: [{name:'小杉らぁめん　夢番地',description:'細ストレート麺に鶏白湯スープが絡む。あっさりしているが濃厚な矛盾を孕む一杯。',rating:3.48},{ name:'らぁ麺　はやし田　武蔵小杉店',description:'INGS系の醤油ラーメン。安定したおいしさを提供してくれる安心の一杯。',rating:3.58},] },
 { id: 'den-en-chofu', name: '田園調布', position: { top: '78.73%', left: '18.33%' }, ramenShops: [] },
 { id: 'futako-tamagawa', name: '二子玉川', position: { top: '67.03%', left: '8.88%' }, ramenShops: [] },
 { id: 'setagaya-daita', name: '世田谷代田', position: { top: '55.00%', left: '13.80%' }, ramenShops: [] },
 { id: 'kugayama', name: '久我山', position: { top: '39.02%', left: '9.87%' }, ramenShops: [] },
 { id: 'ogikubo', name: '荻窪', position: { top: '33.30%', left: '9.53%' }, ramenShops: [{name:'ラーメン二郎　荻窪店',description:'食事時間１５分制限の二郎。デフォで豚１枚なので実際は１５分もかからないので安心して食べられる。',rating:3.68},] },
 { id: 'minami-senju', name: '南千住', position: { top: '26.35%', left: '75.55%' }, ramenShops: [] },
 { id: 'machiya', name: '町屋', position: { top: '16.83%', left: '70.83%' }, ramenShops: [] },
 { id: 'itabashi', name: '板橋', position: { top: '19.82%', left: '37.20%' }, ramenShops: [] },
 { id: 'mukojima', name: '東向島', position: { top: '28.69%', left: '81.65%' }, ramenShops: [] },
 { id: 'oji-kamiya', name: '王子神谷', position: { top: '9.04%', left: '48.72%' }, ramenShops: [] },
 { id: 'shin-itabashi', name: '新板橋', position: { top: '13.96%', left: '36.60%' }, ramenShops: [] },
 { id: 'sugamo', name: '巣鴨', position: { top: '21.23%', left: '46.99%' }, ramenShops: [] },
 { id: 'komagome', name: '駒込', position: { top: '21.47%', left: '53.10%' }, ramenShops: [] },
 { id: 'tabata', name: '田端', position: { top: '24.33%', left: '56.72%' }, ramenShops: [] },
 { id: 'oshima', name: '大島', position: { top: '47.86%', left: '85.43%' }, ramenShops: [] },
 { id: 'nishi-ojima', name: '西大島', position: { top: '47.78%', left: '84.04%' }, ramenShops: [] },
 { id: 'higashi-ojima', name: '東大島', position: { top: '47.78%', left: '86.70%' }, ramenShops: [] },
 { id: 'funabori', name: '船堀', position: { top: '47.74%', left: '88.03%' }, ramenShops: [] },
 { id: 'ichinoe', name: '一之江', position: { top: '47.82%', left: '89.33%' }, ramenShops: [] },
 { id: 'mizue', name: '瑞江', position: { top: '47.86%', left: '90.71%' }, ramenShops: [] },
 { id: 'shinozaki', name: '篠崎', position: { top: '47.82%', left: '91.90%' }, ramenShops: [] },
 { id: 'motoyawata', name: '本八幡', position: { top: '47.21%', left: '94.02%' }, ramenShops: [] },
 { id: 'koenji', name: '高円寺', position: { top: '33.30%', left: '12.09%' }, ramenShops: [] },
 { id: 'asagaya', name: '阿佐ヶ谷', position: { top: '33.25%', left: '10.87%' }, ramenShops: [{name:'無冠 阿佐ヶ谷',description:'大量の牡蠣から出た出汁を使った牡蠣塩ラーメン。麺量も多く、リーズナブルに高品櫃のラーメンを楽しめる。',rating:3.67},] },
 { id: 'nishi-ogikubo', name: '西荻窪', position: { top: '33.25%', left: '7.94%' }, ramenShops: [] },
 { id: 'mitaka', name: '三鷹', position: { top: '33.25%', left: '0.85%' }, ramenShops: [] },
 { id: 'musashisakai', name: '武蔵境', position: { top: '27.52%', left: '4.67%' }, ramenShops: [] },
 { id: 'takaido', name: '高井戸', position: { top: '41.93%', left: '11.87%' }, ramenShops: [] },
 { id: 'kugayama-keio', name: '久我山', position: { top: '39.02%', left: '9.84%' }, ramenShops: [] },
 { id: 'inokashira-koen', name: '井の頭公園', position: { top: '36.12%', left: '7.79%' }, ramenShops: [] },
 { id: 'shimo-takaido', name: '下高井戸', position: { top: '48.59%', left: '10.67%' }, ramenShops: [] },
 { id: 'sakurajosui', name: '桜上水', position: { top: '48.39%', left: '8.14%' }, ramenShops: [] },
 { id: 'shinjuku-sanchome', name: '新宿三丁目', position: { top: '41.24%', left: '35.46%' }, ramenShops: [] },
 { id: 'higashi-shinjuku', name: '東新宿', position: { top: '37.33%', left: '35.37%' }, ramenShops: [] },
 { id: 'nishi-waseda', name: '西早稲田', position: { top: '35.63%', left: '35.77%' }, ramenShops: [{name:'ラーメン富士丸　西早稲田店',description:'富士丸系特有のワシワシ触感の麺が豚のうまみ出たスープと絡む。少し醤油感は弱め。',rating:3.58},{ name:'末廣ラーメン本舗　高田馬場分店',description:'秋田ブラックともいうべき塩味がかなり効いた一杯。苦手な人はバターを頼めば円やかになる。',rating:3.52},{ name:'ピコピコポン',description:'元住吉「豚星。」出身のインスパイア、麺量は少な目でクタヤサイ、パンチにあふれた一杯。',rating:3.68}] },
 { id: 'zoshigaya', name: '雑司が谷', position: { top: '31.03%', left: '35.57%' }, ramenShops: [] },
 { id: 'gokokuji', name: '護国寺', position: { top: '29.49%', left: '45.16%' }, ramenShops: [{ name:'MENSHO',description:'醤油の甘味が前面に出たすべての素材にこだわられた一杯。トッピングのフライドえのきを沈めればスープが一変する',rating:3.80}] },
 { id: 'edogawabashi', name: '江戸川橋', position: { top: '31.03%', left: '45.16%' }, ramenShops: [{ name:'三ん寅',description:'純すみ系の味噌ラーメン。動物系のコクと味噌の円やかさを感じる一杯',rating:3.86}] },
 { id: 'akabane', name: '赤羽', position: { top: '7.99%', left: '38.87%' }, ramenShops: [] },
 { id: 'kita-akabane', name: '北赤羽', position: { top: '6.78%', left: '36.65%' }, ramenShops: [] },
 { id: 'arakawa-kosen', name: '荒川区役所前', position: { top: '23.04%', left: '72.06%' }, ramenShops: [] },
 { id: 'hiken-koen', name: '飛鳥山', position: { top: '11.62%', left: '49.37%' }, ramenShops: [] },
 { id: 'kasai', name: '葛西', position: { top: '55.81%', left: '87.85%' }, ramenShops: [] },
 { id: 'urayasu', name: '浦安', position: { top: '55.85%', left: '89.16%' }, ramenShops: [] },
 { id: 'gyotoku', name: '行徳', position: { top: '55.93%', left: '91.55%' }, ramenShops: [] },
 { id: 'myoden', name: '妙典', position: { top: '56.05%', left: '92.80%' }, ramenShops: [] },
 
 { id: 'kokkai-gijidomae', name: '国会議事堂前', position: { top: '61.70%', left: '49.49%' }, ramenShops: [] },
 { id: 'roppongi-itchome', name: '六本木一丁目', position: { top: '68.32%', left: '48.21%' }, ramenShops: [] },
 { id: 'kamiyacho', name: '神谷町', position: { top: '66.50%', left: '51.28%' }, ramenShops: [] },
 { id: 'shiba-koen', name: '芝公園', position: { top: '71.39%', left: '55.63%' }, ramenShops: [] },
 { id: 'ryogoku', name: '両国', position: { top: '42.70%', left: '77.77%' }, ramenShops: [] },
 { id: 'sumiyoshi', name: '住吉', position: { top: '47.86%', left: '82.16%' }, ramenShops: [] },
 { id: 'hatchobori', name: '八丁堀', position: { top: '63.24%', left: '77.18%' }, ramenShops: [{name:'麺や 七彩',description:'目の前で粉から麺を作ってくれるエンタメ満載ながらも味も都内随一の名店。無難に醤油をおすすめしたい。',rating:3.78},] },
 { id: 'kayabacho', name: '茅場町', position: { top: '57.38%', left: '76.89%' }, ramenShops: [] },
 { id: 'suitengumae', name: '水天宮前', position: { top: '54.56%', left: '76.55%' }, ramenShops: [] },
 { id: 'ningyocho', name: '人形町', position: { top: '52.70%', left: '74.13%' }, ramenShops: [] },
 { id: 'kodemmacho', name: '小伝馬町', position: { top: '48.99%', left: '70.15%' }, ramenShops: [] },
 { id: 'shin-nihonbashi', name: '新日本橋(三越前)', position: { top: '52.10%', left: '69.95%' }, ramenShops: [] },
 { id: 'takebashi', name: '竹橋', position: { top: '54.80%', left: '50.57%' }, ramenShops: [] },
 { id: 'kudanshita', name: '九段下', position: { top: '49.96%', left: '50.65%' }, ramenShops: [] },
 { id: 'myogadani', name: '茗荷谷', position: { top: '24.42%', left: '46.27%' }, ramenShops: [] },
 { id: 'kanamecho', name: '要町', position: { top: '21.27%', left: '29.25%' }, ramenShops: [{name:'中華そば　しながわ',description:'シンプルな醤油ラーメンながらも麺ののど越しやスープのうまみなど細かい点までもピカイチな一杯。',rating:3.74},] },
 { id: 'kotake-mukaihara', name: '小竹向原', position: { top: '16.46%', left: '24.30%' }, ramenShops: [] },
 { id: 'nerima', name: '練馬', position: { top: '20.78%', left: '17.39%' }, ramenShops: [] },
 { id: 'waseda', name: '早稲田', position: { top: '34.26%', left: '41.44%' }, ramenShops: [] },
 { id: 'kagurazaka', name: '神楽坂', position: { top: '34.26%', left: '44.54%' }, ramenShops: [] },
 { id: 'higashi-nakano', name: '東中野', position: { top: '34.18%', left: '17.36%' }, ramenShops: [] },
 { id: 'hatagaya', name: '幡ヶ谷', position: { top: '46.85%', left: '24.22%' }, ramenShops: [] },
 { id: 'sasazuka', name: '笹塚', position: { top: '47.79%', left: '20.49%' }, ramenShops: [] },
 { id: 'den-en-chofu', name: '田園調布', position: { top: '78.73%', left: '18.33%' }, ramenShops: [] },
 { id: 'futako-tamagawa', name: '二子玉川', position: { top: '67.03%', left: '8.88%' }, ramenShops: [] },
 { id: 'setagaya-daita', name: '世田谷代田', position: { top: '55.00%', left: '13.80%' }, ramenShops: [] },
 { id: 'kugayama', name: '久我山', position: { top: '39.02%', left: '9.87%' }, ramenShops: [] },
 { id: 'minami-senju', name: '南千住', position: { top: '26.35%', left: '75.55%' }, ramenShops: [] },
 { id: 'machiya', name: '町屋', position: { top: '16.83%', left: '70.83%' }, ramenShops: [] },
 { id: 'itabashi', name: '板橋', position: { top: '19.82%', left: '37.20%' }, ramenShops: [] },
 { id: 'mukojima', name: '東向島', position: { top: '28.69%', left: '81.65%' }, ramenShops: [] },
 { id: 'higashi-jujo', name: '東十条', position: { top: '9.89%', left: '43.11%' }, ramenShops: [] },
 { id: 'oji-kamiya', name: '王子神谷', position: { top: '9.04%', left: '48.72%' }, ramenShops: [] },
 { id: 'shin-itabashi', name: '新板橋', position: { top: '13.96%', left: '36.60%' }, ramenShops: [] },
 { id: 'sugamo', name: '巣鴨', position: { top: '21.23%', left: '46.99%' }, ramenShops: [] },
 { id: 'komagome', name: '駒込', position: { top: '21.47%', left: '53.10%' }, ramenShops: [] },
 { id: 'tabata', name: '田端', position: { top: '24.33%', left: '56.72%' }, ramenShops: [] },
 { id: 'oshima', name: '大島', position: { top: '47.86%', left: '85.43%' }, ramenShops: [] },
 { id: 'nishi-ojima', name: '西大島', position: { top: '47.78%', left: '84.04%' }, ramenShops: [] },
 { id: 'higashi-ojima', name: '東大島', position: { top: '47.78%', left: '86.70%' }, ramenShops: [] },
 { id: 'funabori', name: '船堀', position: { top: '47.74%', left: '88.03%' }, ramenShops: [] },
 { id: 'ichinoe', name: '一之江', position: { top: '47.82%', left: '89.33%' }, ramenShops: [] },
 { id: 'mizue', name: '瑞江', position: { top: '47.86%', left: '90.71%' }, ramenShops: [] },
 { id: 'shinozaki', name: '篠崎', position: { top: '47.82%', left: '91.90%' }, ramenShops: [] },
 { id: 'motoyawata', name: '本八幡', position: { top: '47.21%', left: '94.02%' }, ramenShops: [] },
 { id: 'koenji', name: '高円寺', position: { top: '33.30%', left: '12.09%' }, ramenShops: [] },
 { id: 'mitaka', name: '三鷹', position: { top: '33.25%', left: '0.85%' }, ramenShops: [] },
 { id: 'musashisakai', name: '武蔵境', position: { top: '27.52%', left: '4.67%' }, ramenShops: [] },
 { id: 'takaido', name: '高井戸', position: { top: '41.93%', left: '11.87%' }, ramenShops: [] },
 { id: 'kugayama-keio', name: '久我山', position: { top: '39.02%', left: '9.84%' }, ramenShops: [] },
 { id: 'inokashira-koen', name: '井の頭公園', position: { top: '36.12%', left: '7.79%' }, ramenShops: [] },
 { id: 'shimo-takaido', name: '下高井戸', position: { top: '48.59%', left: '10.67%' }, ramenShops: [] },
 { id: 'sakurajosui', name: '桜上水', position: { top: '48.39%', left: '8.14%' }, ramenShops: [] },
 { id: 'chitose-karasuyama', name: '千歳船橋', position: { top: '55.16%', left: '8.05%' }, ramenShops: [{name:'らーめんMAIKAGURA',description:'東京鶏白湯で最先端を走る小麦までこだわりぬかれた純白の一杯。',rating:3.91},] },
 { id: 'zoshigaya', name: '雑司が谷', position: { top: '31.03%', left: '35.57%' }, ramenShops: [] },
 { id: 'akabane', name: '赤羽', position: { top: '7.99%', left: '38.87%' }, ramenShops: [] },
 { id: 'kita-akabane', name: '北赤羽', position: { top: '6.78%', left: '36.65%' }, ramenShops: [] },
 { id: 'arakawa-kosen', name: '荒川区役所前', position: { top: '23.04%', left: '72.06%' }, ramenShops: [] },
 { id: 'hiken-koen', name: '飛鳥山', position: { top: '11.62%', left: '49.37%' }, ramenShops: [] },
 { id: 'kasai', name: '葛西', position: { top: '55.81%', left: '87.85%' }, ramenShops: [] },
 { id: 'urayasu', name: '浦安', position: { top: '55.85%', left: '89.16%' }, ramenShops: [] },
 { id: 'gyotoku', name: '行徳', position: { top: '55.93%', left: '91.55%' }, ramenShops: [] },
 { id: 'myoden', name: '妙典', position: { top: '56.05%', left: '92.80%' }, ramenShops: [] },
 { id: 'shin-otsuka', name: '新大塚', position: { top: '24.46%', left: '43.77%' }, ramenShops: [] },
 { id: 'shimo-maruko', name: '下丸子', position: { top: '93.14%', left: '26.38%' }, ramenShops: [{name:'奈つやの中華そば',description:'「びぎ屋」出身の2024で最も話題となった新店。煮干しが基調となっているが癖はなく、ワンタンももち麦を使用していて触感もよく美味しすぎる最高の一杯。',rating:3.95},]}, 
 { id: 'musashi-nitta', name: '武蔵新田', position: { top: '93.14%', left: '31.20%' }, ramenShops: []},
 { id: 'yaguchinowatashi', name: '矢口渡', position: { top: '93.10%', left: '36.23%' }, ramenShops: []}, 
 { id: 'numabe', name: '沼部', position: { top: '85.35%', left: '16.08%' }, ramenShops: []}, 
 { id: 'okayama-meguro', name: '大岡山', position: { top: '76.23%', left: '24.27%' }, ramenShops: [] }, 
 { id: 'senzoku', name: '洗足', position: { top: '74.13%', left: '25.53%' }, ramenShops: [] }, 
 { id: 'musashi-koyama-meguro', name: '武蔵小山', position: { top: '73.73%', left: '29.42%' }, ramenShops: [] },  
 { id: 'hibarigaoka', name: 'ひばりヶ丘', position: { top: '20.98%', left: '5.92%' }, ramenShops: [{name:'ラーメン二郎　ひばりヶ丘駅前店',description:'ジロリアンの中で宗教的にあがめられている店。乳化したスープに美しいヤサイの盛り、豚の旨味だけで構成されてるんじゃないかと思うくらいおいしい一杯。',rating:3.81},] }, 
 { id: 'heiwadai', name: '平和台', position: { top: '7.95%', left: '15.88%' }, ramenShops: [] }, 
 { id: 'wakoshi', name: '和光市', position: { top: '6.10%', left: '8.25%' }, ramenShops: [{ name:'麺屋　樹真',description:'出汁感のあるスープに高加水率の麺がおいしい。トッピングの筍にも注目。',rating:3.60}] }, 
 { id: 'asaka', name: '朝霞', position: { top: '5.61%', left: '5.55%' }, ramenShops: [{ name:'中華蕎麦　瑞山',description:'麺線の整ったのど越しのよいパツパツ麺に甘めの醤油スープが絶品。しっとりしたチャーシューも甘めに仕上げられている。',rating:3.71}] }, 
 { id: 'ukimafunado-jr', name: '浮間舟渡', position: { top: '5.12%', left: '35.51%' }, ramenShops: [] },
 { id: 'itabashihoncho-jr', name: '板橋本町', position: { top: '10.70%', left: '34.21%' }, ramenShops: [] },
 { id: 'otsuka-jr-yamanote', name: '大塚', position: { top: '21.14%', left: '39.89%' }, ramenShops: [] },
 { id: 'mejiro-jr-yamanote', name: '目白', position: { top: '27.64%', left: '31.16%' }, ramenShops: [] },
 { id: 'gaien-mae', name: '外苑前', position: { top: '59.89%', left: '38.16%' }, ramenShops: [] },
 { id: 'korakuen-m', name: '後楽園', position: { top: '34.87%', left: '53.10%' }, ramenShops: [] },
 { id: 'otemachi-m', name: '大手町', position: { top: '55.25%', left: '57.97%' }, ramenShops: [] },
 { id: 'naka-okachimachi-h', name: '仲御徒町', position: { top: '40.03%', left: '67.50%' }, ramenShops: [] },
 { id: 'tatsumi-y', name: '辰巳', position: { top: '66.83%', left: '84.04%' }, ramenShops: [] },
 { id: 'nogizaka', name: '乃木坂', position: { top: '61.70%', left: '36.45%' }, ramenShops: [] },
 { id: 'akase', name: '赤坂', position: { top: '63.07%', left: '39.10%' }, ramenShops: [] },
 { id: 'keisei-takasago', name: '京成高砂', position: { top: '20.42%', left: '87.65%' }, ramenShops: [] },
 { id: 'keisei-koiwa', name: '京成小岩', position: { top: '20.10%', left: '89.44%' }, ramenShops: [] },
 { id: 'tokyu-fudomae', name: '不動前', position: { top: '73.81%', left: '30.76%' }, ramenShops: [] },
 { id: 'maihama-jr', name: '舞浜', position: { top: '63.11%', left: '92.90%' }, ramenShops: [] },
 { id: 'kokusai-tenjijo-rinkai', name: '国際展示場', position: { top: '80.39%', left: '78.52%' }, ramenShops: [] },
 { id: 'kachidoki', name: '勝どき', position: { top: '71.31%', left: '77.89%' }, ramenShops: [] },
 { id: 'odakyu-seijogakuen-mae', name: '成城学園前', position: { top: '55.00%', left: '5.66%' }, ramenShops: [] },
 { id: 'uchisaiwaicho', name: '内幸町', position: { top: '64.85%', left: '56.66%' }, ramenShops: [] },
 {id:'tamagawa',name:'多摩川',position:{top:'79.05%',left:'16.16%'},ramenShops:[]},
 {id:'motosumiyosi',name:'元住吉',position:{top:'83.82%',left:'8.56%'},ramenShops:[{ name:'豚星。',description:'旨すぎる二郎インスパイヤ。店内は独特の雰囲気があるが、味を知ってしまえばもう気にならない。慶應生なら必食の一杯。',rating:3.74}]},
 {id:'unoki',name:'鵜の木',position:{top:'93.26%',left:'20.83%'},ramenShops:[]},
 {id:'kugahara',name:'久が原',position:{top:'92.62%',left:'21.85%'},ramenShops:[]},
 {id:'ontakeyama',name:'御嶽山',position:{top:'83.37%',left:'19.34%'},ramenShops:[]},
 {id:'yukigawaootuka',name:'雪が谷大塚',position:{top:'80.47%',left:'20.89%'},ramenShops:[{ name:'らぁめん　葉月',description:'モチモチの太麺、醤油の深みを感じるスープに鶏油の甘味がマッチ。これだけジューシーなメンマは他では食べられない。',rating:3.77}]},
 {id:'isikawadai',name:'石川台',position:{top:'80.47%',left:'22.11%'},ramenShops:[]},
 {id:'senzokuike',name:'洗足池',position:{top:'80.47%',left:'23.55%'},ramenShops:[]},
 {id:'nagahara',name:'長原',position:{top:'80.47%',left:'24.89%'},ramenShops:[]},
 {id:'hatanodai',name:'旗の台',position:{top:'79.90%',left:'27.69%'},ramenShops:[]},
 {id:'ebaranakanobu',name:'荏原中延',position:{top:'77.68%',left:'30.36%'},ramenShops:[]},
 {id:'togosiginza',name:'戸越銀座',position:{top:'77.68%',left:'31.47%'},ramenShops:[]},
 {id:'oosakihirokouji',name:'大崎広小路',position:{top:'77.68%',left:'32.58%'},ramenShops:[]},
 {id:'tidorimati',name:'千鳥町',position:{top:'92.86%',left:'30.33%'},ramenShops:[]},
 {id:'ikegami',name:'池上',position:{top:'92.86%',left:'34.46%'},ramenShops:[]},
 {id:'hasunuma',name:'蓮沼',position:{top:'92.86%',left:'38.65%'},ramenShops:[]},
 {id:'oomori',name:'大森',position:{top:'93.66%',left:'45.82%'},ramenShops:[]},
 {id:'kaminakazato',name:'上中里',position:{top:'19.53%',left:'54.21%'},ramenShops:[]},
 {id:'oji',name:'王子',position:{top:'9.56%',left:'51.08%'},ramenShops:[]},
 {id:'takatu',name:'高津',position:{top:'67.19%',left:'4.72%'},ramenShops:[]},
 {id:'hutakosinti',name:'二子新地',position:{top:'67.19%',left:'5.75%'},ramenShops:[]},
 {id:'kaminoge',name:'上野毛',position:{top:'68.80%',left:'11.81%'},ramenShops:[{name:'ラーメン二郎　上野毛店',description:'非乳化、キャベツ多めが特徴の二郎。液アもそれなりにあるが、カラメを入れればキリっとした味を楽しめる。',rating:3.68},]},
 {id:'todoroki',name:'等々力',position:{top:'70.30%',left:'12.95%'},ramenShops:[]},
 {id:'oyamadai',name:'尾山台',position:{top:'71.91%',left:'14.20%'},ramenShops:[]},
 {id:'kuhonbutu',name:'九品仏',position:{top:'73.61%',left:'15.39%'},ramenShops:[]},
 {id:'midorigaoka',name:'緑ヶ丘',position:{top:'75.22%',left:'22.31%'},ramenShops:[{name:'中華蕎麦　三藤',description:'素材にこだわった甘味を感じる醤油ラーメン。色とは裏腹に円やかで癖になる一杯。',rating:3.68},]},
 {id:'kamitisato',name:'北千束',position:{top:'77.96%',left:'26.15%'},ramenShops:[]},
 {id:'ebaramati',name:'荏原町',position:{top:'83.70%',left:'30.28%'},ramenShops:[]},
{id:'nakanobu',name:'中延',position:{top:'84.91%',left:'33.10%'},ramenShops:[]},
 {id:'togosiginza',name:'戸越公園',position:{top:'84.83%',left:'38.28%'},ramenShops:[]},
 {id:'simokamiaki',name:'下神明',position:{top:'84.79%',left:'45.14%'},ramenShops:[]},
 {id:'nisiooi',name:'西大井',position:{top:'88.39%',left:'42.34%'},ramenShops:[]},
 {id:'oosaki',name:'大崎',position:{top:'80.14%',left:'42.63%'},ramenShops:[]},
 {id:'daikanyama',name:'代官山',position:{top:'62.06%',left:'29.14%'},ramenShops:[]},
 {id:'yutenji',name:'祐天寺',position:{top:'69.57%',left:'24.21%'},ramenShops:[{ name:'Ramen Break Beats',description:'柴咲亭仕込みの麺線、天草大王のうまみたっぷりのスープ、全体のバランスさながら鶏の味を最大限に引き出した本当においしい一杯。',rating:3.92},{ name:'博多ラーメン　琉',description:'東京でクサウマ濃厚豚骨ラーメンが食べられる稀有な店。背油が浮いていて甘味を感じる',rating:3.50}]},
 {id:'gakugeidaigaku',name:'学芸大学',position:{top:'71.63%',left:'22.06%'},ramenShops:[{ name:'麺処　びぎ屋　学芸大学本店',description:'うまみたっぷりの醤油スープ、噛み応えとジューシーさを備えたチャーシュー、パツパツの麺、どれをとっても一級品の最高の一杯。',rating:3.77},]},
 {id:'toritudaigaku',name:'都立大学',position:{top:'73.36%',left:'20.26%'},ramenShops:[]},
 {id:'sinmaruko',name:'新丸子',position:{top:'79.05%',left:'14.09%'},ramenShops:[]},
 {id:'magome',name:'馬込',position:{top:'86.56%',left:'31.93%'},ramenShops:[]},
 {id:'togosi',name:'戸越',position:{top:'80.87%',left:'36.03%'},ramenShops:[]},
 {id:'takaramati',name:'宝町',position:{top:'61.18%',left:'74.61%'},ramenShops:[]},
 {id:'nhigasinihonbasi',name:'東日本橋',position:{top:'46.21%',left:'76.07%'},ramenShops:[]},
 {id:'asakusabasi',name:'浅草橋',position:{top:'42.78%',left:'74.73%'},ramenShops:[{ name:'饗　くろ㐂',description:'高級感に溢れた一杯。素材の一つ一つのこだわりが半端でなく、計算されつくした秀逸な一杯。',rating:3.91},]},
 {id:'kuramae',name:'蔵前',position:{top:'38.58%',left:'74.84%'},ramenShops:[]},
 {id:'honjoagatumabasi',name:'本所我妻橋',position:{top:'35.35%',left:'77.52%'},ramenShops:[]},
 {id:'osiage',name:'押上',position:{top:'35.47%',left:'81.36%'},ramenShops:[]},
 {id:'keiseihunabiki',name:'京成船曳',position:{top:'30.06%',left:'84.64%'},ramenShops:[]},
 {id:'yahiro',name:'八広',position:{top:'28.29%',left:'84.68%'},ramenShops:[]},
 {id:'yotugi',name:'四ツ木',position:{top:'26.39%',left:'84.68%' },ramenShops:[]},
 {id:'keiseitateisi',name:'京成立石',position:{top:'24.49%',left:'84.68%'},ramenShops:[]},
 {id:'aoto',name:'青砥',position:{top:'19.45%',left:'84.67%'},ramenShops:[]},
 {id:'keiseihatiman',name:'京成八幡',position:{top:'40.59%',left:'94.45%'},ramenShops:[]},
 {id:'sugano',name:'菅野',position:{top:'38.17%',left:'93.17%'},ramenShops:[]},
 {id:'itikawamama',name:'市川真間',position:{top:'33.50%',left:'93.17%'},ramenShops:[]},
 {id:'kokuhudai',name:'国府台',position:{top:'29.05%',left:'93.17%'},ramenShops:[]},
 {id:'edogawa',name:'江戸川',position:{top:'24.42%',left:'93.17%'},ramenShops:[]},
 {id:'ohanajaya',name:'お花茶屋',position:{top:'20.02%',left:'83.64%'},ramenShops:[]},
 {id:'horikirisyoubuen',name:'堀切菖蒲園',position:{top:'20.10%',left:'82.47%'},ramenShops:[]},
 {id:'keiseisekiya',name:'京成関屋',position:{top:'21.63%',left:'78.99%'},ramenShops:[]},
 {id:'senjuoohasi',name:'千住大橋',position:{top:'19.93%',left:'73.65%'},ramenShops:[{name:'ラーメン二郎千住大橋駅前店',description:'非乳化で豚の旨味がえげつない二郎。量は目黒くらい少ない。コールにラー油があるのが特徴。',rating:3.71},]},
 {id:'sinmikawajima',name:'新三河島',position:{top:'22.40%',left:'65.54%'},ramenShops:[]},
 {id:'mikawajima',name:'三河島',position:{top:'27.56%',left:'68.42%'},ramenShops:[]},
 {id:'sintomityo',name:'新富町',position:{top:'65.54%',left:'72.68%'},ramenShops:[{name:'燎',description:'スープは蔦、麺は七彩と名店のいいところをハイブリッドしたような夢の一杯。深みのある醤油スープにもちもちの麺が絶品。',rating:3.85},]},
 {id:'kojimati',name:'麹町',position:{top:'49.52%',left:'47.10%'},ramenShops:[]},
 {id:'hikawadai',name:'氷川台',position:{top:'11.66%',left:'18.61%'},ramenShops:[]},
 {id:'heiwadai',name:'平和台',position:{top:'7.87%',left:'15.91%'},ramenShops:[]},
 {id:'tikatetuakatuka',name:'地下鉄赤塚',position:{top:'6.89%',left:'12.18%'},ramenShops:[]},
 {id:'tikatetunarimasu',name:'地下鉄成増',position:{top:'7.02%',left:'10.07%'},ramenShops:[{ name:'ラーメン武蔵家　HANARE',description:'一般的な武蔵家とは異なり低温調理のチャーシュー、醤油がバチバチに効いた豚骨スープ、すべてが好みだ。',rating:3.51},{ name:'中華めん処　道頓堀',description:'創業４０年を超える超老舗。あっさりとした動物と魚介の効いたスープを巻き込むストレート麺。誰もがおいしいといえる一杯。',rating:3.74},{ name:'花木流味噌　成増総本店',description:'標準的な味噌ラーメン。特筆することがないがブレも少ない」普通の味噌ラーメン',rating:3.43},{ name:'中華そば　べんてん',description:'節系の力強いスープに高加水率のツルツル麺、メンマも存在感を放ち、すべてにおいておいしい一杯。',rating:3.80}]},
 {id:'narimasu',name:'成増',position:{top:'5.57%',left:'10.02%'},ramenShops:[]},
 {id:'simoakatuka',name:'下赤塚',position:{top:'5.69%',left:'13.09%'},ramenShops:[]},
 {id:'tobunerima',name:'東武練馬',position:{top:'12.27%',left:'20.15%' },ramenShops:[]},
 {id:'kamiitabasi',name:'上板橋',position:{top:'14.16%',left:'21.51%' },ramenShops:[]},
 {id:'tokiwadai',name:'ときわ台',position:{top:'14.89%',left:'24.36%' },ramenShops:[]},
 {id:'nakaitabasi',name:'中板橋',position:{top:'14.89%',left:'27.41%' },ramenShops:[]},
 {id:'kitaikebukuro',name:'北池袋',position:{top:'23.45%',left:'33.47%' },ramenShops:[]},
 {id:'simoitabasi',name:'下板橋',position:{top:'19.61%',left:'32.70%' },ramenShops:[]},
 {id:'oyama',name:'大山',position:{top:'15.94%',left:'30.02%' },ramenShops:[]},
 {id:'siinamati',name:'椎名町',position:{top:'23.36%',left:'26.66%' },ramenShops:[]},
 {id:'higasinagasaki',name:'東長崎',position:{top:'21.71%',left:'25.55%' },ramenShops:[{name:'カネキッチン　ヌードル',description:'鶏を真っ先に感じる鶏清湯スープ。醤油が鶏を巧く引き立てていて最後まで飽きないおいしさ。',rating:3.78},]},
 {id:'sakuradai',name:'桜台',position:{top:'20.86%',left:'22.88%' },ramenShops:[]},
 {id:'sinsakuradai',name:'新桜台',position:{top:'17.88%',left:'21.23%' },ramenShops:[]},
 {id:'nakamurabasi',name:'中村橋',position:{top:'20.90%',left:'13.55%' },ramenShops:[]},
 {id:'hujimidai',name:'富士見台',position:{top:'20.90%',left:'12.27%' },ramenShops:[]},
 {id:'nerimatakanodai',name:'練馬高野台',position:{top:'20.90%',left:'10.99%' },ramenShops:[]},
 {id:'syakujikouen',name:'石神井公園',position:{top:'20.90%',left:'9.70%' },ramenShops:[]},
 {id:'ooizumigakuen',name:'大泉学園',position:{top:'20.90%',left:'8.45%' },ramenShops:[]},
 {id:'hoya',name:'保谷',position:{top:'20.90%',left:'7.17%' },ramenShops:[]},
 {id:'higasikurume',name:'東久留米',position:{top:'20.90%',left:'4.64%' },ramenShops:[]},
 {id:'kamisyakujii',name:'上石神井',position:{top:'27.52%',left:'5.89%' },ramenShops:[]},
 {id:'kamiigusa',name:'上井草',position:{top:'27.52%',left:'7.09%' },ramenShops:[]},
 {id:'ihagi',name:'井萩',position:{top:'27.52%',left:'8.28%' },ramenShops:[]},
 {id:'simoigusa',name:'下井草',position:{top:'27.52%',left:'9.45%' },ramenShops:[]},
 {id:'saginomiya',name:'鷺ノ宮',position:{top:'27.52%',left:'10.64%' },ramenShops:[]},
 {id:'toritukasei',name:'都立家政',position:{top:'27.52%',left:'11.78%' },ramenShops:[]},
 {id:'nokata',name:'野方',position:{top:'27.52%',left:'12.98%' },ramenShops:[]},
 {id:'numabukuro',name:'沼袋',position:{top:'27.52%',left:'14.17%' },ramenShops:[]},
 {id:'araiyakusimae',name:'新井薬師前',position:{top:'27.52%',left:'15.34%' },ramenShops:[]},
 {id:'nakai',name:'中井',position:{top:'27.52%',left:'17.76%' },ramenShops:[]},
 {id:'simootiai',name:'下落合',position:{top:'29.10%',left:'22.68%' },ramenShops:[]},
 {id:'otiai',name:'落合',position:{top:'30.63%',left:'19.04%' },ramenShops:[]},
 {id:'okubo',name:'大久保',position:{top:'33.94%',left:'21.34%' },ramenShops:[]},
 {id:'sendagaya',name:'千駄ヶ谷',position:{top:'48.09%',left:'32.98%' },ramenShops:[]},
 {id:'sinanomati',name:'信濃町',position:{top:'48.05%',left:'37.08%' },ramenShops:[]},
 {id:'kameido',name:'亀戸',position:{top:'41.93%',left:'87.99%' },ramenShops:[{ name:'ラーメン二郎亀戸店',description:'都内二郎の中でも随一の非乳化で神豚。店内の雰囲気も明るく、二郎初心者におすすめの一杯。',rating:3.69}]},
 {id:'hirai',name:'平井',position:{top:'43.06%',left:'89.44%' },ramenShops:[]},
 {id:'sinkoiwa',name:'新小岩',position:{top:'43.10%',left:'90.43%' },ramenShops:[]},
 {id:'koiwa',name:'小岩',position:{top:'43.10%',left:'91.41%' },ramenShops:[{name:'ラーメン二郎小岩店',description:'二郎の中でも来訪難易度は高め。脂にこだわっており、アブラコールは必須といえる。',rating:3.70},]},
 {id:'itikawa',name:'市川',position:{top:'43.10%',left:'92.43%' },ramenShops:[]},
 {id:'simousanakayama',name:'下総中山',position:{top:'52.42%',left:'93.86%' },ramenShops:[]},
 {id:'genbokunakayama',name:'原木中山',position:{top:'55.81%',left:'93.97%' },ramenShops:[]},
 {id:'minamigyoutoku',name:'南行徳',position:{top:'55.81%',left:'90.30%' },ramenShops:[]},
 {id:'nisikasai',name:'西葛西',position:{top:'55.81%',left:'86.66%' },ramenShops:[]},
 {id:'minamisunamati',name:'南砂町',position:{top:'55.81%',left:'85.43%' },ramenShops:[]},
 {id:'toyotyo',name:'東陽町',position:{top:'55.89%',left:'84.24%' },ramenShops:[]},
 {id:'kiba',name:'木場',position:{top:'55.81%',left:'83.04%' },ramenShops:[]},
 {id:'mitakadai',name:'三鷹台',position:{top:'37.65%',left:'8.88%' },ramenShops:[]},
 {id:'hujimigaoka',name:'富士見ヶ丘',position:{top:'40.52%',left:'10.87%' },ramenShops:[]},
 {id:'hamadayama',name:'浜田山',position:{top:'43.14%',left:'12.75%' },ramenShops:[]},
 {id:'nisieihuku',name:'西永福',position:{top:'44.55%',left:'13.75%' },ramenShops:[]},
 {id:'eihukutyo',name:'永福町',position:{top:'45.76%',left:'14.59%' },ramenShops:[]},
 {id:'higasimatubara',name:'東松原',position:{top:'50.36%',left:'15.91%' },ramenShops:[]},
 {id:'sindaita',name:'新代田',position:{top:'52.80%',left:'15.91%' },ramenShops:[{name:'ラーメン二郎　環七新新代田店',description:'極太麺の非乳化二郎.豚のうまみに醤油のキレがバチっと効いた一杯。',rating:3.66},]},
 {id:'ikenoue',name:'池ノ上',position:{top:'58.39%',left:'17.59%' },ramenShops:[]},
 {id:'komabatodaimae',name:'駒場東大前',position:{top:'59.28%',left:'23.19%' },ramenShops:[]},
 {id:'sinsen',name:'神泉',position:{top:'59.28%',left:'27.29%' },ramenShops:[{ name:'喜楽',description:'都内随一のもやしラーメン。動物系のスープにフライドオニオンが香ばしさを与え、唯一無二の味を形成している。',rating:3.76}]},
 {id:'ikejiriohasi',name:'池尻大橋',position:{top:'59.93%',left:'25.50%' },ramenShops:[{ name:'八雲',description:'プリップリのワンタン、滋味にあふれたスープ。すべてにおいて完成度の高い感動の一杯。',rating:3.77}]},
 {id:'sangendyaya',name:'三軒茶屋',position:{top:'64.93%',left:'21.12%' },ramenShops:[]},
 {id:'komazawadaigaku',name:'駒澤大学',position:{top:'66.87%',left:'17.64%' },ramenShops:[]},
 {id:'sakurasinmati',name:'桜新町',position:{top:'66.87%',left:'15.68%' },ramenShops:[]},
 {id:'yoga',name:'用賀',position:{top:'66.87%',left:'13.39%' },ramenShops:[]},
 {id:'nisitaisidou',name:'西太子堂',position:{top:'64.85%',left:'19.69%' },ramenShops:[]},
 {id:'wakabayasi',name:'若林',position:{top:'64.85%',left:'18.09%' },ramenShops:[]},
 {id:'syoinjinjamae',name:'松陰神社前',position:{top:'64.85%',left:'16.39%' },ramenShops:[]},
 {id:'setagaya',name:'世田谷',position:{top:'64.85%',left:'14.54%' },ramenShops:[]},
 {id:'kamimati',name:'上町',position:{top:'64.85%',left:'12.50%' },ramenShops:[]},
 {id:'miyanozaka',name:'宮野坂',position:{top:'61.18%',left:'10.16%' },ramenShops:[]},
 {id:'yamasita',name:'山下',position:{top:'52.50%',left:'10.42%' },ramenShops:[]},
 {id:'matubara',name:'松原',position:{top:'50.16%',left:'10.19%' },ramenShops:[]},
 {id:'kitami',name:'喜多見',position:{top:'55.08%',left:'4.52%' },ramenShops:[]},
 {id:'sosigayaookura',name:'祖師ヶ谷大蔵',position:{top:'55.08%',left:'6.86%' },ramenShops:[{name:'ラーメン荘　歴史を刻め　世田谷',description:'関東唯一の歴史を刻め。アブラに麺をくぐらせて口に入れれば背徳感満載だが脳が昇天するほどのおいしさ。',rating:3.59},]},
 {id:'gotokuji',name:'豪徳寺',position:{top:'55.93%',left:'11.10%' },ramenShops:[]},
 {id:'umegaoka',name:'梅が丘',position:{top:'55.08%',left:'12.61%' },ramenShops:[]},
 {id:'higasikitazawa',name:'東北沢',position:{top:'55.00%',left:'18.18%' },ramenShops:[]},
 {id:'yoyogihatiman',name:'代々木八幡',position:{top:'50.97%',left:'22.59%' },ramenShops:[]},
 {id:'sangubasi',name:'参宮橋',position:{top:'46.45%',left:'25.78%' },ramenShops:[]},
 {id:'minamisinjuku',name:'南新宿',position:{top:'44.87%',left:'26.92%' },ramenShops:[{ name:'風雲児　新宿本店',description:'鶏白湯と魚介をかけ合わせた濃厚なスープがかなりこってりとしていてスープによく絡む。',rating:3.77},]},
 {id:'rokakouen',name:'芦花公園',position:{top:'48.43%',left:'4.99%' },ramenShops:[]},
 {id:'hatimanyama',name:'八幡山',position:{top:'48.47%',left:'6.06%' },ramenShops:[]},
 {id:'kamikitazawa',name:'上北沢',position:{top:'48.47%',left:'7.14%' },ramenShops:[]},
 {id:'daitabasi',name:'代田橋',position:{top:'48.47%',left:'19.15%' },ramenShops:[]},
 {id:'hatudai',name:'初台',position:{top:'45.08%',left:'25.41%' },ramenShops:[]},
 {id:'minamiasagaya',name:'南阿佐ヶ谷',position:{top:'35.55%',left:'9.93%' },ramenShops:[]},
 {id:'sinkouenji',name:'新高円寺',position:{top:'37.04%',left:'11.12%' },ramenShops:[]},
 {id:'higasikouenji',name:'東高円寺',position:{top:'38.90%',left:'13.49%' },ramenShops:[{name:'だしと麺 遊泳',description:'ラーメンとは言い難いが究極の油そばを提供してくれる行列必死の名店。麺はうどん屋さんで修行されたようです。',rating:3.84},{name:'豚骨 蒼翔',description:'ワンタンが乗った豚骨100％の家系ラーメン。鶏油は少な目にして豚骨を味わうことをおすすめしたい。',rating:3.71},]},
 {id:'sinakano',name:'新中野',position:{top:'38.98%',left:'15.00%' },ramenShops:[]},
 {id:'honantyo',name:'方南町',position:{top:'44.11%',left:'16.16%' },ramenShops:[{ name:'クラム＆ボニート　貝節麺ライク',description:'店名の通り貝が前面に出たあっさりとしたラーメン。貝の旨味が凝縮された一杯。',rating:3.75},]},
 {id:'nakanohujimityo',name:'中野富士見町',position:{top:'42.29%',left:'16.16%' },ramenShops:[{name:'純手打ち　だるま',description:'七彩出身の店主が提供する手打ち麺があっさり醤油スープと絡んで美味しい。麺も美味しいがスープもそれに負けず存在感を放つ。',rating:3.87},]},
 {id:'nakanosinbasi',name:'中野新橋',position:{top:'40.48%',left:'16.13%' },ramenShops:[]},
 {id:'nisisinjuku',name:'西新宿',position:{top:'38.98%',left:'22.80%' },ramenShops:[]},
 {id:'yotuyasantyome',name:'四谷三丁目',position:{top:'45.19%',left:'38.73%' },ramenShops:[]},
 {id:'akasakamituke',name:'赤坂見附',position:{top:'60.94%',left:'45.79%' },ramenShops:[]},
 {id:'awajityo',name:'淡路町',position:{top:'52.95%',left:'59.48%' },ramenShops:[]},
 {id:'omotesando',name:'表参道',position:{top:'59.64%',left:'35.37%' },ramenShops:[]},
 {id:'aoyamaityoume',name:'青山一丁目',position:{top:'60.50%',left:'40.69%' },ramenShops:[]},
 {id:'hanzomon',name:'半蔵門',position:{top:'50.56%',left:'49.03%' },ramenShops:[]},
 {id:'toranomon',name:'虎ノ門',position:{top:'65.82%',left:'54.50%' },ramenShops:[]},
 {id:'uenohirokouji',name:'上野広小路',position:{top:'40.72%',left:'60.05%' },ramenShops:[]},
 {id:'inarimati',name:'稲荷町',position:{top:'33.50%',left:'69.41%' },ramenShops:[]},
 {id:'omorikaigan',name:'大森海岸',position:{top:'93.87%',left:'51.17%' },ramenShops:[]},
 {id:'tatiaigawa',name:'立会川',position:{top:'92.45%',left:'51.17%' },ramenShops:[]},
 {id:'samesu',name:'鮫洲',position:{top:'90.88%',left:'51.17%' },ramenShops:[]},
 {id:'aomonoyokotyo',name:'青物横丁',position:{top:'88.29%',left:'51.17%' },ramenShops:[]},
 {id:'sinbaba',name:'新馬場',position:{top:'86.56%',left:'51.17%' },ramenShops:[]},
 {id:'kitasinagawa',name:'北品川',position:{top:'84.83%',left:'51.17%' },ramenShops:[{name:'中華そば　和渦　TOKYO',description:'キリっとしたた口当たりのスープに細麺が合わさりクオリティの高さを見せつけてくる、満足感の高い一杯。',rating:3.79},{name:'ラーメン二郎　品川店',description:'二郎の中では食べやすいあっさりとした二郎。麺量も一般的（３００弱）で撃沈する人も少ない。',rating:3.71},]},
 {id:'tukijisijo',name:'築地市場',position:{top:'71.27%',left:'71.89%' },ramenShops:[]},
 {id:'kasairinkaikoen',name:'葛西臨海公園',position:{top:'63.16%',left:'86.91%' },ramenShops:[]},
 {id:'siomi',name:'潮見',position:{top:'63.56%',left:'83.24%' },ramenShops:[]},
 {id:'etyuujima',name:'越中島',position:{top:'63.56%',left:'80.99%' },ramenShops:[]},
 {id:'akebonobasi',name:'曙橋',position:{top:'40.92%',left:'40.64%' },ramenShops:[]},
 {id:'iwamototyo',name:'岩本町',position:{top:'47.98%',left:'66.56%' },ramenShops:[{name:'青島食堂　秋葉原店',description:'都内NO1の新潟生姜醤油ラーメン。さっぱりとしていて食後感もよく、アキバに来たら絶対に食べる一杯。',rating:3.74},]},
 {id:'bakuroyokoyama',name:'馬喰横山',position:{top:'47.25%',left:'73.28%' },ramenShops:[]},
 {id:'hamatyo',name:'浜町',position:{top:'47.86%',left:'77.58%' },ramenShops:[]},
 {id:'nisitakasimadaira',name:'西高島平',position:{top:'6.38%',left:'23.96%' },ramenShops:[]},
 {id:'sintakasimadaira',name:'新高島平',position:{top:'6.38%',left:'25.87%' },ramenShops:[]},
 {id:'takasimadaira',name:'高島平',position:{top:'6.38%',left:'27.35%' },ramenShops:[]},
 {id:'nisidai',name:'西台',position:{top:'6.38%',left:'28.46%' },ramenShops:[]},
 {id:'hasune',name:'蓮根',position:{top:'6.38%',left:'29.96%' },ramenShops:[]},
 {id:'simurasantyome',name:'志村三丁目',position:{top:'6.38%',left:'31.13%' },ramenShops:[]},
 {id:'simurasakaue',name:'志村坂上',position:{top:'8.15%',left:'32.33%' },ramenShops:[]},
 {id:'motohasunuma',name:'本蓮沼',position:{top:'9.40%',left:'33.24%' },ramenShops:[]},
 {id:'itabasikuyakusyomae',name:'板橋区役所前',position:{top:'11.91%',left:'35.09%' },ramenShops:[{name:'あさひ町内会',description:'純すみ系の味噌ラーメン。ラードによってアツアツが保たれた味噌の甘味を感じるスープは黄金色の麺と絡んで最高だ。',rating:3.80},]},
 {id:'nisisugamo',name:'西巣鴨',position:{top:'14.33%',left:'40.01%' },ramenShops:[]},
 {id:'sengoku',name:'千石',position:{top:'23.96%',left:'47.87%' },ramenShops:[]},
 {id:'sirayama',name:'白山',position:{top:'25.10%',left:'47.87%' },ramenShops:[]},
 {id:'hibiya',name:'日比谷',position:{top:'60.81%',left:'57.43%' },ramenShops:[]},
 {id:'hiro',name:'広尾',position:{top:'67.11%',left:'37.56%' },ramenShops:[]},
 {id:'iriya',name:'入谷',position:{top:'30.39%',left:'69.99%' },ramenShops:[{name:'麺処　晴',description:'煮干しの旨味たっぷりの煮干しラーメン。煮干しの持っているポテンシャルをすべてを一杯に詰め合わせた一杯。',rating:3.79},]},
 {id:'kitaayase',name:'北綾瀬',position:{top:'10.82%', left: '80.02%' }, ramenShops:[]},
 {id:'ayase',name:'綾瀬',position:{top:'12.23%', left: '78.32%' }, ramenShops:[]},
 {id:'sendagi',name:'千駄木',position:{top:'29.74%', left: '57.68%' }, ramenShops:[]},
 {id:'yoyogikoekn',name:'代々木公園',position:{top:'53.75%', left: '26.86%' }, ramenShops:[]},
 {id:'kitasando',name:'北参道',position:{top:'51.98%', left: '35.77%' }, ramenShops:[]},
 {id:'hikarigaoka',name:'光が丘',position:{top:'13.52%', left: '15.51%' }, ramenShops:[]},
 {id:'nerimakasugatyou',name:'練馬春日町',position:{top:'14.85%', left: '16.45%' }, ramenShops:[]},
 {id:'tosimaen',name:'豊島園',position:{top:'16.55%', left: '17.33%' }, ramenShops:[]},
 {id:'sinegota',name:'新江古田',position:{top:'22.64%', left: '17.70%' }, ramenShops:[]},
 {id:'otiaihigasinagasaki',name:'落合東長崎',position:{top:'25.54%', left: '17.70%' }, ramenShops:[]},
 {id:'uenookatimati',name:'上野御徒町',position:{top:'37.41%', left: '60.88%' }, ramenShops:[]},
 {id: 'kamata',name: '蒲田',position: { top: '94.71%', left: '41.03%' },ramenShops: [{name:'らーめん飛粋 ',description:'NEO家系にふさわしいマイルドな家系。スモークされたチャーシューも絶品でラーメンの進化を感じる一杯',rating:3.78},],},
 {id:'sinokatimati',name:'新御徒町',position:{top:'36.68%', left: '70.02%' }, ramenShops:[{name:'らーめん天神下 大喜',description:'鶏の旨味が濃密に凝縮された一杯。トッピングの柚子胡椒を沈めればさっぱりと最後まで飽きなく食べられる。',rating:3.74},]},
 {id:'kokuritukyougijou',name:'国立競技場',position:{top:'52.90%', left: '37.36%' }, ramenShops:[{name:'ラーメンの店　ホープ軒　千駄ヶ谷店',description:'背脂チャッチャ系の元祖ともいうべき背脂にあふれた一杯。見た目はこってりしていますが、実際はそれほどあっさりしています。',rating:3.68},]},
 {id:'jujo',name:'十条',position:{top:'11.58%', left: '37.96%' }, ramenShops:[]},
 {id:'ogu',name:'尾久',position:{top:'16.55%', left: '55.41%' }, ramenShops:[]},
 {id:'kyodo',name:'経堂',position:{top:'55.00%', left: '9.20%' }, ramenShops:[]},
 {id:'simo',name:'志茂',position:{top:'9.20%', left: '46.99%' }, ramenShops:[]},
 {id:'nisigahara',name:'西ヶ原',position:{top:'12.63%', left: '53.24%' }, ramenShops:[]},
 {id:'honkomagome',name:'本駒込',position:{top:'24.29%', left: '53.29%' }, ramenShops:[]},
 {id:'todaimae',name:'東大前',position:{top:'26.07%', left: '53.29%' }, ramenShops:[]},
 {id:'kameidosuijin',name:'亀戸水神',position:{top:'36.68%', left:'87.99%'}, ramenShops:[]},
 {id:'higasiazuma',name:'東あずま',position:{top:'33.25%', left:'86.99%'}, ramenShops:[]},
 {id:'komurai',name:'小村井',position:{top:'33.01%', left:'85.77%'}, ramenShops:[]},
 {id:'hunabiki',name:'船曳',position:{top:'32.97%', left:'81.63%'}, ramenShops:[]},
 {id:'kanigahuti',name:'鐘ヶ淵',position:{top:'26.03%', left:'81.76%'}, ramenShops:[]},
 {id:'horikiri',name:'堀切',position:{top:'22.72%', left:'81.73%'}, ramenShops:[]},
 {id:'usita',name:'牛田',position:{top:'17.98%', left:'78.91%'}, ramenShops:[]},
 {id:'kosuga',name:'小菅',position:{top:'14.00%', left:'76.70%'}, ramenShops:[]},
 {id:'gotanno',name:'五反野',position:{top:'12.63%', left:'73.59%'}, ramenShops:[]},
 {id:'umejima',name:'梅島',position:{top:'11.58%', left:'72.79%'}, ramenShops:[]},
 {id:'nisiarai',name:'西新井',position:{top:'8.88%', left:'71.06%'}, ramenShops:[]},
 {id:'daisimae',name:'大師前',position:{top:'7.06%', left:'68.53%'}, ramenShops:[]},
 {id:'takenotuka',name:'竹ノ塚',position:{top:'7.63%', left:'71.03%'}, ramenShops:[]},
 {id:'tanituka',name:'谷塚',position:{top:'6.22%', left:'71.06%'}, ramenShops:[]},
 {id:'souka',name:'草加',position:{top:'4.64%', left:'71.09%'}, ramenShops:[]},
 {id:'sibamata',name:'柴又',position:{top:'17.19%', left:'87.51%'}, ramenShops:[]},
 {id:'kanemati',name:'金町（京成金町）',position:{top:'13.68%', left:'85.97%'}, ramenShops:[]},
 {id:'kameari',name:'亀有',position:{top:'12.63%', left:'83.84%' }, ramenShops:[]},
 {id:'sijoumae',name:'市場前',position:{top:'79.18%',left:'81.93%'}, ramenShops:[]},
 {id:'ariaketenisunomori',name:'有明テニスの森',position:{top:'81.40%',left:'80.80%'}, ramenShops:[]},
 {id:'kokusaitenjijoumae',name:'国際展示場前',position:{top:'84.39%',left:'77%'}, ramenShops:[]},
 {id:'oumi',name:'青海',position:{top:'84.54%',left:'75.9%'}, ramenShops:[]},
{id:'terekomusenta-',name:'テレコムセンター',position:{top:'84.34%',left:'74.70%'}, ramenShops:[]},
{id:'hunenokagakukan',name:'船の科学館',position:{top:'84.38%',left:'73.47%'}, ramenShops:[]},
 {id:'daiba',name:'台場',position:{top:'81.40%',left:'71.74%'}, ramenShops:[]},
 {id:'waseda-toden',name:'早稲田（都電）',position:{top:'33.30%',left:'38.59%'}, ramenShops:[]},
 {id:'omokagebasi',name:'面影橋',position:{top:'31.76%',left:'37.56%'}, ramenShops:[{name:'やまぐち',description:'鶏水系の醤油ラーメン。角のない優しい口当たりのスープがすすり心地のよいスープに纏わりつき、本当においしい。',rating:3.79},]},
 {id:'gakusyuinsita',name:'学習院下',position:{top:'30.18%',left:'37.59%'}, ramenShops:[]},
 {id:'tukumogamimae',name:'鬼子母神前',position:{top:'28.77%',left:'39.05%'}, ramenShops:[]},
 {id:'todenzousigaya',name:'都電雑司ヶ谷',position:{top:'27.44%',left:'37.56%'}, ramenShops:[]},
 {id:'mukoubara',name:'向原',position:{top:'23.61%',left:'40.00%'}, ramenShops:[]},
 {id:'sigasiikebukuroyontyo-me',name:'東池袋',position:{top:'25.58%',left:'39.70%'}, ramenShops:[{name:'塩そば専門店　桑ばら',description:'サンシャイン通りの離れにある塩ラーメン屋。最後に塩の結晶を感じるほど塩味が強いが慣れると大山鳥のおいしさを感じる。塩ラーメンの権威ともいえる一杯。',rating:3.68},]},
 {id:'sugamosinden',name:'巣鴨新田',position:{top:'18.56%',left:'42.79%'}, ramenShops:[]},
 {id:'kosinduka',name:'庚申塚',position:{top:'17.27%',left:'42.76%'}, ramenShops:[]},
 {id:'sinkosinduka',name:'新庚申塚',position:{top:'16.22%',left:'42.76%'}, ramenShops:[]},
 {id:'nisigararayontyome',name:'西ヶ原四丁目',position:{top:'14.73%',left:'45.05%'}, ramenShops:[]},
 {id:'sakaemati',name:'栄町',position:{top:'8.03%',left:'53.19%'}, ramenShops:[]},
 {id:'kajiwara',name:'梶原',position:{top:'8.07%',left:'54.21%'}, ramenShops:[]},
 {id:'arakawasyakomae',name:'荒川車庫前',position:{top:'9.64%',left:'55.51%'}, ramenShops:[]},
 {id:'arakawayuentimae',name:'荒川遊園地前',position:{top:'11.46%',left:'56.86%'}, ramenShops:[]},
 {id:'odai',name:'小台',position:{top:'12.55%',left:'57.57%'}, ramenShops:[]},
 {id:'miyanomae',name:'宮ノ前',position:{top:'13.96%',left:'58.60%'}, ramenShops:[]},
 {id:'kumanomae',name:'熊野前',position:{top:'14.81%',left:'61.41%'}, ramenShops:[]},
 {id:'higasiogusantyome',name:'東尾久三丁目',position:{top:'14.90%',left:'65.76%'}, ramenShops:[{name:'Ramen にじゅうぶんのいち ',description:'美味しい鶏清湯。インパクトにはかけるものの、チャーシューはとんでもないうまさ。',rating:8.32},]},
 {id:'matiyanityome',name:'町屋二丁目',position:{top:'14.90%',left:'69.13%'}, ramenShops:[]},
 {id:'arakawananatyome',name:'荒川七丁目',position:{top:'19.93%',left:'72.06%'}, ramenShops:[]},
 {id:'arakawanityome',name:'荒川二丁目',position:{top:'21.43%',left:'72.06%' }, ramenShops:[]},
 {id:'arakawaityumae',name:'荒川一中前',position:{top:'24.50%',left:'72.06%' }, ramenShops:[]},
 {id:'minowabasi',name:'三ノ輪橋',position:{top:'25.91%',left:'72.06%' }, ramenShops:[]},
 {id:'uguisudani',name:'鶯谷',position:{top:'30.75%',left:'63.77%' }, ramenShops:[]},
 {id:'nisiarakawataisinisi',name:'西荒川大師西',position:{top:'6.78%',left:'61.18%' }, ramenShops:[]},
 {id:'ekita',name:'江北',position:{top:'8.20%',left:'61.18%' }, ramenShops:[]},
 {id:'takano',name:'高野',position:{top:'9.73%',left:'61.18%' }, ramenShops:[]},
 {id:'ougioohasi',name:'扇大橋',position:{top:'11.22%',left:'61.18%' }, ramenShops:[]},
 {id:'adatiodai',name:'足立小台',position:{top:'12.75%',left:'61.22%' }, ramenShops:[]},
 {id:'akatutisyogakkoumae',name:'赤土小学校前',position:{top:'16.55%',left:'61.15%' }, ramenShops:[]},
 {id:'sinonome',name:'東雲',position:{top:'78.05%',left:'85.12%' }, ramenShops:[]},
 {id:'sinagawasi-saido',name:'品川シーサイド',position:{top:'87.45%',left:'55.37%' }, ramenShops:[]},
 {id:'ooikeibajoumae',name:'大井競馬場前',position:{top:'84.87%',left:'57.46%' }, ramenShops:[]},
 {id:'ryutu-senta-',name:'流通センター',position:{top:'86.19%',left:'57.49%' }, ramenShops:[]},
 {id:'syowajima',name:'昭和島',position:{top:'87.37%',left:'57.49%' }, ramenShops:[]},
 {id:'seibijo',name:'整備場',position:{top:'88.50%',left:'57.49%' }, ramenShops:[]},
 {id:'tenkubasi',name:'天空橋',position:{top:'91.81%',left:'57.49%' }, ramenShops:[]},
 {id:'takinogawaittyoume',name:'滝野川一丁目',position:{top:'12.83%',left:'49.37%' }, ramenShops:[]},
 {id:'nisikoyama',name:'西小山',position:{top:'73.69%',left:'27.72%' }, ramenShops:[]},
 {id:'okusawa',name:'奥沢',position:{top:'79.38%',left:'20.55%' }, ramenShops:[]},

{id:'kikukawa',name:'菊川',position:{top:'47.90%',left:'80.79%'},ramenShops:[]},
{id:'morisita',name:'森下',position:{top:'47.90%',left:'79.52%'},ramenShops:[]},
{id:'bakurotyo',name:'馬喰町',position:{top:'46.04%',left:'70.89%'},ramenShops:[]},
{id:'kiyosumisirakawa',name:'清澄白河',position:{top:'54.68%',left:'80.05%'},ramenShops:[]},
{id:'tukisima',name:'月島',position:{top:'66.87%',left:'79.43%'},ramenShops:[]},
{id:'minowa',name:'三ノ輪',position:{top:'30.59%',left:'72.74%'},ramenShops:[]},
{id:'akabaneiwabuti',name:'赤羽岩淵',position:{top:'7.18%',left:'45.82%'},ramenShops:[]},
{id:'oimati',name:'大井町',position:{top:'88.50%',left:'47.07%'},ramenShops:[]},
{id:'tennousuairu',name:'天王洲アイル',position:{top:'82.90%',left:'59.31%'},ramenShops:[]},
{id:'toukyouterepo-to',name:'東京テレポート',position:{top:'82.81%',left:'75.75%'},ramenShops:[]},
{id:'sibaurahutou',name:'芝浦ふ頭',position:{top:'75.42%',left:'66.56%'},ramenShops:[]},
{id:'hinode',name:'日の出',position:{top:'73.69%',left:'66.56%'},ramenShops:[]},
{id:'takesiba',name:'竹芝',position:{top:'71.96%',left:'66.56%'},ramenShops:[]},
{id:'ogawamati',name:'小川町',position:{top:'49.60%',left:'59.79%'},ramenShops:[]},
{id:'sinotyanomizu',name:'新御茶ノ水',position:{top:'48.43%',left:'56.37%'},ramenShops:[]},
{id:'yusima',name:'湯島',position:{top:'39.95%',left:'57.68%'},ramenShops:[]},
{id:'nedu',name:'根津',position:{top:'31.88%',left:'57.74%'},ramenShops:[]},
{id:'usigomekagurazaka',name:'牛込神楽坂',position:{top:'37.37%',left:'45.69%'},ramenShops:[]},
{id:'usigomeyanagimati',name:'牛込柳町',position:{top:'37.37%',left:'41.72%'},ramenShops:[]},
{id:'wakamatukawata',name:'若松河田',position:{top:'37.37%',left:'38.33%'},ramenShops:[]},
{id:'sintoyosu',name:'新豊洲',position:{top:'75.34%',left:'81.90%'},ramenShops:[]},
{ id: 'nisihunabasi', name: '西船橋', position: { top: '55.81%', left: '95.65%' }, ramenShops: [] },
{id:'akabanebasi',name:'赤羽橋',position:{top:'69.93%',left:'51.31%'},ramenShops:[]},
{id:'sirokanetakanawa',name:'白金高輪',position:{top:'73.69%',left:'45.14%'},ramenShops:[]},
{id:'takanawadai',name:'高輪台',position:{top:'76.40%',left:'42.57%'},ramenShops:[]},
{id:'sirokanedai',name:'白金台',position:{top:'73.36%',left:'40.47%'},ramenShops:[]},
{id:'hirosue',name:'末広町',position:{top:'45.28%',left:'61.98%'},ramenShops:[]},
{id:'nisimagome',name:'西馬込',position:{top:'89.95%',left:'29.71%'},ramenShops:[]},
{id:'hutaebasimae',name:'二重橋前',position:{top:'57.09%',left:'57.65%'},ramenShops:[]},
{id:'taharatyo',name:'田原町',position:{top:'33.62%',left:'72.65%'},ramenShops:[]},
{id:'kosuga',name:'小菅',position:{top:'15.54%',left:'76.63%'},ramenShops:[]}





];



// アプリのメインの部分。ここに書かれた内容がウェブサイトに表示されます。
function App() {
  // `selectedStation` は、今、どの駅のラーメン情報が表示されているかを記憶する箱です。
  // `setSelectedStation` は、その箱の中身を変更するための命令です。
  // 最初は何も表示されていないので `null`（空っぽ）です。
  const [selectedStation, setSelectedStation] = React.useState(null);

  // 駅のボタンがクリックされたときに動く命令です。
  // クリックされた駅の情報を `selectedStation` に記憶させます。
  const handleStationClick = (station) => {
    setSelectedStation(station);
  };

  // ラーメン情報が表示されているポップアップ（モーダル）の「閉じる」ボタンがクリックされたときに動く命令です。
  // `selectedStation` を空っぽにして、ポップアップを閉じます。
  const handleCloseModal = () => {
    setSelectedStation(null);
  };

  return (
    // アプリ全体の入れ物となる一番外側の箱
    <div className="App">
      {/* 路線図を表示するエリア。CSSで背景画像を設定します。 */}
      <div className="map-container">
        {/* この img タグは、CSSで背景画像を設定するためにも必要です。 */}
        <img src={lineImage} alt="東京路線図" className="line-map-image" />

        {/*
          stationDataの各駅の情報を使って、一つずつボタンを作ります。
          map() は、リストの項目を一つずつ取り出して何かをするための命令です。
        */}
        {stationData.map((station) => (
          // 駅のボタン
          <button
            key={station.id} // それぞれのボタンを区別するための名前（重要！）
            className="station-button" // CSSで見た目を設定するための名前
            // ボタンの位置を、stationDataで設定したtopとleftに合わせて決めます
            style={{ top: station.position.top, left: station.position.left }}
            // このボタンがクリックされたら、handleStationClickの命令を実行します
            onClick={() => handleStationClick(station)}
          >
            {station.name} {/* ボタンに表示される駅の名前 */}
          </button>
        ))}
      </div>

      {/*
        ラーメン屋さんの情報が表示されるポップアップ（モーダル）の部分。
        `selectedStation && (...)` は、「もしselectedStationに何か情報が入っていたら(...)の中身を表示する」という意味です。
        つまり、駅のボタンがクリックされた時だけ表示されます。
      */}
      {selectedStation && (
        <div className="modal-overlay"> {/* ポップアップの背景（半透明の黒い部分） */}
          <div className="modal-content"> {/* ポップアップの中身 */}
            <h2>{selectedStation.name} のラーメン屋さん</h2> {/* クリックされた駅の名前を表示 */}
            {selectedStation.ramenShops.length > 0 ? ( // ラーメン情報がある場合
              <ul> {/* ラーメン屋さんのリスト */}
                {/*
                  選択された駅のramenShops（ラーメン屋さんリスト）を一つずつ取り出して表示します。
                */}
                {selectedStation.ramenShops.map((shop, index) => (
                  <li key={index}> {/* リストの項目一つ一つ */}
                    <h3>{shop.name}</h3> {/* ラーメン屋さんの名前 */}
                    <p>{shop.description}</p> {/* ラーメン屋さんの説明 */}
                    <p>評価: {shop.rating} / 5</p> {/* ラーメン屋さんの評価 */}
                  </li>
                ))}
              </ul>
            ) : ( // ラーメン情報がない場合
              <p>この駅には現在、おすすめのラーメン情報がありません。</p>
            )}
            {/* ポップアップを閉じるボタン */}
            <button onClick={handleCloseModal} className="close-button">閉</button>
          </div>
        </div>
      )}
    </div>
  );
}

// このAppコンポーネントを他のファイルでも使えるようにするおまじない
export default App;